const english = {
  title: 'Profile settings', intro: 'Your profile. Your radio.', profile: 'Profile', details: 'Personal details',
  name: 'Full name', email: 'Email', password: 'Password', passwordHint: 'Leave blank to keep your current password.',
  country: 'Country', language: 'Language', selectCountry: 'Select a country',
  playback: 'Play at log in', autoplay: 'Autoplay', autoplayHint: 'Start a station automatically when you sign in.',
  lastPlayed: 'Last Played', random: 'Random', favorite: 'Favorite',
  publicProfile: 'Public profile', privacyHint: 'Let other listeners see your profile and favorite stations.',
  changeAvatar: 'Change profile picture', avatarHint: 'JPG, PNG or WebP · up to 5 MB', followers: 'Followers', following: 'Following',
  save: 'Save Changes', saving: 'Saving…', cancel: 'Discard changes', unsaved: 'You have unsaved changes.',
  saved: 'Your changes have been saved.', saveFailed: 'Could not save your changes. Please try again.',
  error: 'Error', success: 'Success', nameInvalid: 'Enter a name of 1–200 characters.', emailInvalid: 'Enter a valid email address.',
  passwordInvalid: 'Use at least 8 characters and no more than 72 bytes.',
  avatarSaved: 'Your profile picture has been updated.', avatarFailed: 'Could not upload this image. Please try again.',
  notifications: 'Notifications', notificationsHint: 'Choose whether to receive push notifications in this browser.',
  unsupported: 'Push notifications are not supported in this browser.', blocked: 'Blocked', enabled: 'Enabled', disabled: 'Disabled',
  enableNotifications: 'Enable notifications', disableNotifications: 'Disable notifications', testNotification: 'Send a test',
  notificationBlockedHint: 'Allow notifications for this site in your browser settings, then reload the page.',
} as const;

export type ProfileSettingsCopy = { [K in keyof typeof english]: string };
const keys = Object.keys(english) as (keyof ProfileSettingsCopy)[];

// Keep these fallbacks local to settings. The current locale's admin dictionary
// wins; a missing entry must not silently inherit the global English dictionary.
const rows: Record<string, readonly string[]> = {
  de: ['Profileinstellungen', 'Dein Profil. Dein Radio.', 'Profil', 'Persönliche Angaben', 'Vollständiger Name', 'E-Mail', 'Passwort', 'Leer lassen, um dein aktuelles Passwort zu behalten.', 'Land', 'Sprache', 'Land auswählen', 'Wiedergabe beim Anmelden', 'Automatische Wiedergabe', 'Starte beim Anmelden automatisch einen Sender.', 'Zuletzt gehört', 'Zufälliger Sender', 'Favorit', 'Öffentliches Profil', 'Andere können dein Profil und deine Lieblingssender sehen.', 'Profilbild ändern', 'JPG, PNG oder WebP · bis zu 5 MB', 'Follower', 'Gefolgt', 'Änderungen speichern', 'Wird gespeichert…', 'Änderungen verwerfen', 'Du hast ungespeicherte Änderungen.', 'Deine Änderungen wurden gespeichert.', 'Deine Änderungen konnten nicht gespeichert werden. Bitte versuche es erneut.', 'Fehler', 'Erfolg', 'Gib einen Namen mit 1–200 Zeichen ein.', 'Gib eine gültige E-Mail-Adresse ein.', 'Verwende mindestens 8 Zeichen und höchstens 72 Bytes.', 'Dein Profilbild wurde aktualisiert.', 'Das Bild konnte nicht hochgeladen werden. Bitte versuche es erneut.', 'Benachrichtigungen', 'Wähle, ob du Push-Benachrichtigungen in diesem Browser erhalten möchtest.', 'Dieser Browser unterstützt keine Push-Benachrichtigungen.', 'Blockiert', 'Aktiviert', 'Deaktiviert', 'Benachrichtigungen aktivieren', 'Benachrichtigungen deaktivieren', 'Test senden', 'Erlaube Benachrichtigungen für diese Website in deinen Browsereinstellungen und lade die Seite neu.'],
  tr: ['Profil ayarları', 'Senin profilin. Senin radyon.', 'Profil', 'Kişisel bilgiler', 'Ad soyad', 'E-posta', 'Şifre', 'Mevcut şifreni korumak için boş bırak.', 'Ülke', 'Dil', 'Ülke seç', 'Girişte çal', 'Otomatik oynatma', 'Giriş yaptığında bir istasyonu otomatik başlat.', 'Son dinlenen', 'Rastgele', 'Favori', 'Herkese açık profil', 'Diğer dinleyiciler profilini ve favori istasyonlarını görebilir.', 'Profil fotoğrafını değiştir', 'JPG, PNG veya WebP · en fazla 5 MB', 'Takipçiler', 'Takip edilenler', 'Değişiklikleri kaydet', 'Kaydediliyor…', 'Değişiklikleri iptal et', 'Kaydedilmemiş değişikliklerin var.', 'Değişikliklerin kaydedildi.', 'Değişiklikler kaydedilemedi. Tekrar dene.', 'Hata', 'Başarılı', '1–200 karakter arasında bir ad gir.', 'Geçerli bir e-posta adresi gir.', 'En az 8 karakter ve en fazla 72 bayt kullan.', 'Profil fotoğrafın güncellendi.', 'Resim yüklenemedi. Tekrar dene.', 'Bildirimler', 'Bu tarayıcıda anlık bildirim almak isteyip istemediğini seç.', 'Bu tarayıcı anlık bildirimleri desteklemiyor.', 'Engellendi', 'Etkin', 'Devre dışı', 'Bildirimleri etkinleştir', 'Bildirimleri devre dışı bırak', 'Test gönder', 'Tarayıcı ayarlarında bu site için bildirimlere izin ver ve sayfayı yenile.'],
  es: ['Ajustes del perfil', 'Tu perfil. Tu radio.', 'Perfil', 'Datos personales', 'Nombre completo', 'Correo electrónico', 'Contraseña', 'Déjalo en blanco para mantener tu contraseña actual.', 'País', 'Idioma', 'Selecciona un país', 'Reproducir al iniciar sesión', 'Reproducción automática', 'Inicia una emisora automáticamente al entrar.', 'Última escuchada', 'Aleatoria', 'Favorita', 'Perfil público', 'Permite que otros vean tu perfil y tus emisoras favoritas.', 'Cambiar foto de perfil', 'JPG, PNG o WebP · hasta 5 MB', 'Seguidores', 'Siguiendo', 'Guardar cambios', 'Guardando…', 'Descartar cambios', 'Tienes cambios sin guardar.', 'Tus cambios se han guardado.', 'No se pudieron guardar los cambios. Inténtalo de nuevo.', 'Error', 'Éxito', 'Introduce un nombre de 1–200 caracteres.', 'Introduce un correo electrónico válido.', 'Usa al menos 8 caracteres y como máximo 72 bytes.', 'Tu foto de perfil se ha actualizado.', 'No se pudo subir la imagen. Inténtalo de nuevo.', 'Notificaciones', 'Elige si quieres recibir notificaciones en este navegador.', 'Este navegador no admite notificaciones push.', 'Bloqueadas', 'Activadas', 'Desactivadas', 'Activar notificaciones', 'Desactivar notificaciones', 'Enviar prueba', 'Permite las notificaciones de este sitio en los ajustes del navegador y recarga la página.'],
  fr: ['Paramètres du profil', 'Votre profil. Votre radio.', 'Profil', 'Informations personnelles', 'Nom complet', 'Adresse e-mail', 'Mot de passe', 'Laissez vide pour conserver votre mot de passe actuel.', 'Pays', 'Langue', 'Choisir un pays', 'Lecture à la connexion', 'Lecture automatique', 'Lancez une station automatiquement à la connexion.', 'Dernière écoute', 'Aléatoire', 'Favorite', 'Profil public', 'Permettez aux autres de voir votre profil et vos stations favorites.', 'Changer la photo de profil', 'JPG, PNG ou WebP · 5 Mo maximum', 'Abonnés', 'Abonnements', 'Enregistrer les modifications', 'Enregistrement…', 'Annuler les modifications', 'Vous avez des modifications non enregistrées.', 'Vos modifications ont été enregistrées.', 'Impossible d’enregistrer les modifications. Réessayez.', 'Erreur', 'Succès', 'Saisissez un nom de 1 à 200 caractères.', 'Saisissez une adresse e-mail valide.', 'Utilisez au moins 8 caractères et au maximum 72 octets.', 'Votre photo de profil a été mise à jour.', 'Impossible d’envoyer cette image. Réessayez.', 'Notifications', 'Choisissez si vous souhaitez recevoir des notifications dans ce navigateur.', 'Ce navigateur ne prend pas en charge les notifications push.', 'Bloquées', 'Activées', 'Désactivées', 'Activer les notifications', 'Désactiver les notifications', 'Envoyer un test', 'Autorisez les notifications de ce site dans les paramètres du navigateur, puis actualisez la page.'],
  pt: ['Configurações do perfil', 'Seu perfil. Sua rádio.', 'Perfil', 'Dados pessoais', 'Nome completo', 'E-mail', 'Senha', 'Deixe em branco para manter sua senha atual.', 'País', 'Idioma', 'Selecione um país', 'Reproduzir ao entrar', 'Reprodução automática', 'Inicie uma estação automaticamente ao entrar.', 'Última ouvida', 'Aleatória', 'Favorita', 'Perfil público', 'Permita que outros vejam seu perfil e suas estações favoritas.', 'Alterar foto do perfil', 'JPG, PNG ou WebP · até 5 MB', 'Seguidores', 'Seguindo', 'Salvar alterações', 'Salvando…', 'Descartar alterações', 'Você tem alterações não salvas.', 'Suas alterações foram salvas.', 'Não foi possível salvar as alterações. Tente novamente.', 'Erro', 'Sucesso', 'Digite um nome com 1–200 caracteres.', 'Digite um endereço de e-mail válido.', 'Use pelo menos 8 caracteres e no máximo 72 bytes.', 'Sua foto de perfil foi atualizada.', 'Não foi possível enviar a imagem. Tente novamente.', 'Notificações', 'Escolha se deseja receber notificações neste navegador.', 'Este navegador não suporta notificações push.', 'Bloqueadas', 'Ativadas', 'Desativadas', 'Ativar notificações', 'Desativar notificações', 'Enviar teste', 'Permita as notificações deste site nas configurações do navegador e recarregue a página.'],
  it: ['Impostazioni del profilo', 'Il tuo profilo. La tua radio.', 'Profilo', 'Dati personali', 'Nome completo', 'E-mail', 'Password', 'Lascia vuoto per mantenere la password attuale.', 'Paese', 'Lingua', 'Seleziona un paese', 'Riproduci all’accesso', 'Riproduzione automatica', 'Avvia una stazione automaticamente quando accedi.', 'Ultima ascoltata', 'Casuale', 'Preferita', 'Profilo pubblico', 'Consenti agli altri di vedere il tuo profilo e le tue stazioni preferite.', 'Cambia foto del profilo', 'JPG, PNG o WebP · fino a 5 MB', 'Follower', 'Seguiti', 'Salva modifiche', 'Salvataggio…', 'Annulla modifiche', 'Hai modifiche non salvate.', 'Le modifiche sono state salvate.', 'Impossibile salvare le modifiche. Riprova.', 'Errore', 'Operazione riuscita', 'Inserisci un nome di 1–200 caratteri.', 'Inserisci un indirizzo e-mail valido.', 'Usa almeno 8 caratteri e non più di 72 byte.', 'La foto del profilo è stata aggiornata.', 'Impossibile caricare l’immagine. Riprova.', 'Notifiche', 'Scegli se ricevere notifiche in questo browser.', 'Questo browser non supporta le notifiche push.', 'Bloccate', 'Attive', 'Disattivate', 'Attiva notifiche', 'Disattiva notifiche', 'Invia un test', 'Consenti le notifiche per questo sito nelle impostazioni del browser e ricarica la pagina.'],
  ru: ['Настройки профиля', 'Ваш профиль. Ваше радио.', 'Профиль', 'Личные данные', 'Полное имя', 'Электронная почта', 'Пароль', 'Оставьте поле пустым, чтобы сохранить текущий пароль.', 'Страна', 'Язык', 'Выберите страну', 'Воспроизведение при входе', 'Автовоспроизведение', 'Автоматически включать станцию при входе.', 'Последняя станция', 'Случайная', 'Избранная', 'Открытый профиль', 'Разрешите другим видеть ваш профиль и избранные станции.', 'Изменить фото профиля', 'JPG, PNG или WebP · до 5 МБ', 'Подписчики', 'Подписки', 'Сохранить изменения', 'Сохранение…', 'Отменить изменения', 'У вас есть несохранённые изменения.', 'Изменения сохранены.', 'Не удалось сохранить изменения. Попробуйте снова.', 'Ошибка', 'Готово', 'Введите имя длиной от 1 до 200 символов.', 'Введите действительный адрес электронной почты.', 'Используйте не менее 8 символов и не более 72 байт.', 'Фото профиля обновлено.', 'Не удалось загрузить изображение. Попробуйте снова.', 'Уведомления', 'Выберите, получать ли уведомления в этом браузере.', 'Этот браузер не поддерживает push-уведомления.', 'Заблокированы', 'Включены', 'Выключены', 'Включить уведомления', 'Выключить уведомления', 'Отправить тест', 'Разрешите уведомления для этого сайта в настройках браузера и обновите страницу.'],
  ar: ['إعدادات الملف الشخصي', 'ملفك الشخصي. راديوك.', 'الملف الشخصي', 'البيانات الشخصية', 'الاسم الكامل', 'البريد الإلكتروني', 'كلمة المرور', 'اترك الحقل فارغًا للاحتفاظ بكلمة المرور الحالية.', 'البلد', 'اللغة', 'اختر بلدًا', 'التشغيل عند تسجيل الدخول', 'التشغيل التلقائي', 'شغّل محطة تلقائيًا عند تسجيل الدخول.', 'آخر محطة استمعت إليها', 'عشوائية', 'مفضلة', 'ملف شخصي عام', 'اسمح للآخرين برؤية ملفك الشخصي ومحطاتك المفضلة.', 'تغيير صورة الملف الشخصي', 'JPG أو PNG أو WebP · حتى 5 ميغابايت', 'المتابعون', 'أتابع', 'حفظ التغييرات', 'جارٍ الحفظ…', 'تجاهل التغييرات', 'لديك تغييرات غير محفوظة.', 'تم حفظ التغييرات.', 'تعذر حفظ التغييرات. حاول مرة أخرى.', 'خطأ', 'تم بنجاح', 'أدخل اسمًا من حرف واحد إلى 200 حرف.', 'أدخل عنوان بريد إلكتروني صالحًا.', 'استخدم 8 أحرف على الأقل و72 بايت كحد أقصى.', 'تم تحديث صورة ملفك الشخصي.', 'تعذر تحميل الصورة. حاول مرة أخرى.', 'الإشعارات', 'اختر ما إذا كنت تريد تلقي إشعارات في هذا المتصفح.', 'هذا المتصفح لا يدعم الإشعارات الفورية.', 'محظورة', 'مفعّلة', 'معطّلة', 'تفعيل الإشعارات', 'تعطيل الإشعارات', 'إرسال اختبار', 'اسمح بإشعارات هذا الموقع في إعدادات المتصفح ثم أعد تحميل الصفحة.'],
  zh: ['个人资料设置', '你的资料，你的电台。', '个人资料', '个人信息', '姓名', '电子邮箱', '密码', '留空以保留当前密码。', '国家', '语言', '选择国家', '登录时播放', '自动播放', '登录时自动播放一个电台。', '上次播放', '随机电台', '收藏电台', '公开个人资料', '允许其他听众查看你的资料和收藏的电台。', '更换头像', 'JPG、PNG 或 WebP · 最大 5 MB', '关注者', '正在关注', '保存更改', '正在保存…', '放弃更改', '你有尚未保存的更改。', '你的更改已保存。', '无法保存更改，请重试。', '错误', '成功', '请输入 1–200 个字符的姓名。', '请输入有效的电子邮箱地址。', '至少使用 8 个字符，且不超过 72 字节。', '你的头像已更新。', '无法上传此图片，请重试。', '通知', '选择是否在此浏览器中接收推送通知。', '此浏览器不支持推送通知。', '已屏蔽', '已开启', '已关闭', '开启通知', '关闭通知', '发送测试', '请在浏览器设置中允许此网站发送通知，然后刷新页面。'],
  ja: ['プロフィール設定', 'あなたのプロフィール。あなたのラジオ。', 'プロフィール', '個人情報', '氏名', 'メールアドレス', 'パスワード', '現在のパスワードを維持する場合は空欄にしてください。', '国', '言語', '国を選択', 'ログイン時に再生', '自動再生', 'ログイン時にラジオ局を自動で再生します。', '最後に聴いた局', 'ランダム', 'お気に入り', '公開プロフィール', '他のリスナーがプロフィールとお気に入りの局を閲覧できます。', 'プロフィール画像を変更', 'JPG、PNG、WebP · 最大5 MB', 'フォロワー', 'フォロー中', '変更を保存', '保存中…', '変更を破棄', '保存されていない変更があります。', '変更を保存しました。', '変更を保存できませんでした。もう一度お試しください。', 'エラー', '完了', '1〜200文字の名前を入力してください。', '有効なメールアドレスを入力してください。', '8文字以上、72バイト以内で入力してください。', 'プロフィール画像を更新しました。', '画像をアップロードできませんでした。もう一度お試しください。', '通知', 'このブラウザーでプッシュ通知を受け取るかどうかを選択します。', 'このブラウザーはプッシュ通知に対応していません。', 'ブロック中', '有効', '無効', '通知を有効にする', '通知を無効にする', 'テストを送信', 'ブラウザー設定でこのサイトの通知を許可し、ページを再読み込みしてください。'],
  ko: ['프로필 설정', '나의 프로필. 나의 라디오.', '프로필', '개인 정보', '이름', '이메일', '비밀번호', '현재 비밀번호를 유지하려면 비워 두세요.', '국가', '언어', '국가 선택', '로그인 시 재생', '자동 재생', '로그인하면 방송국을 자동으로 재생합니다.', '마지막으로 들은 방송국', '무작위', '즐겨찾기', '공개 프로필', '다른 청취자가 내 프로필과 즐겨찾는 방송국을 볼 수 있습니다.', '프로필 사진 변경', 'JPG, PNG 또는 WebP · 최대 5 MB', '팔로워', '팔로잉', '변경 사항 저장', '저장 중…', '변경 사항 취소', '저장하지 않은 변경 사항이 있습니다.', '변경 사항을 저장했습니다.', '변경 사항을 저장하지 못했습니다. 다시 시도해 주세요.', '오류', '완료', '1~200자의 이름을 입력하세요.', '유효한 이메일 주소를 입력하세요.', '최소 8자, 최대 72바이트로 입력하세요.', '프로필 사진을 변경했습니다.', '이미지를 업로드하지 못했습니다. 다시 시도해 주세요.', '알림', '이 브라우저에서 푸시 알림을 받을지 선택하세요.', '이 브라우저는 푸시 알림을 지원하지 않습니다.', '차단됨', '켜짐', '꺼짐', '알림 켜기', '알림 끄기', '테스트 보내기', '브라우저 설정에서 이 사이트의 알림을 허용한 후 페이지를 새로고침하세요.'],
  hi: ['प्रोफ़ाइल सेटिंग', 'आपकी प्रोफ़ाइल। आपका रेडियो।', 'प्रोफ़ाइल', 'व्यक्तिगत जानकारी', 'पूरा नाम', 'ईमेल', 'पासवर्ड', 'मौजूदा पासवर्ड रखने के लिए इसे खाली छोड़ें।', 'देश', 'भाषा', 'देश चुनें', 'लॉगिन पर चलाएँ', 'अपने आप चलाएँ', 'लॉगिन करते समय अपने आप एक स्टेशन चलाएँ।', 'पिछली बार सुना गया', 'कोई भी स्टेशन', 'पसंदीदा', 'सार्वजनिक प्रोफ़ाइल', 'दूसरों को अपनी प्रोफ़ाइल और पसंदीदा स्टेशन देखने दें।', 'प्रोफ़ाइल तस्वीर बदलें', 'JPG, PNG या WebP · अधिकतम 5 MB', 'फ़ॉलोअर', 'फ़ॉलो कर रहे हैं', 'बदलाव सहेजें', 'सहेजा जा रहा है…', 'बदलाव रद्द करें', 'आपके कुछ बदलाव सहेजे नहीं गए हैं।', 'आपके बदलाव सहेज दिए गए हैं।', 'बदलाव सहेजे नहीं जा सके। फिर से कोशिश करें।', 'त्रुटि', 'सफल', '1–200 अक्षरों का नाम दर्ज करें।', 'एक मान्य ईमेल पता दर्ज करें।', 'कम से कम 8 अक्षर और अधिकतम 72 बाइट इस्तेमाल करें।', 'आपकी प्रोफ़ाइल तस्वीर अपडेट हो गई है।', 'तस्वीर अपलोड नहीं हो सकी। फिर से कोशिश करें।', 'सूचनाएँ', 'चुनें कि इस ब्राउज़र में पुश सूचनाएँ प्राप्त करनी हैं या नहीं।', 'यह ब्राउज़र पुश सूचनाओं का समर्थन नहीं करता।', 'अवरुद्ध', 'चालू', 'बंद', 'सूचनाएँ चालू करें', 'सूचनाएँ बंद करें', 'परीक्षण भेजें', 'ब्राउज़र सेटिंग में इस साइट की सूचनाओं को अनुमति दें, फिर पेज दोबारा लोड करें।'],
  he: ['הגדרות פרופיל', 'הפרופיל שלך. הרדיו שלך.', 'פרופיל', 'פרטים אישיים', 'שם מלא', 'דואר אלקטרוני', 'סיסמה', 'אפשר להשאיר ריק כדי לשמור על הסיסמה הנוכחית.', 'מדינה', 'שפה', 'בחירת מדינה', 'ניגון בעת הכניסה', 'ניגון אוטומטי', 'הפעלת תחנה אוטומטית בעת הכניסה לחשבון.', 'התחנה האחרונה', 'אקראית', 'מועדפת', 'פרופיל ציבורי', 'מאזינים אחרים יוכלו לראות את הפרופיל ואת התחנות המועדפות שלך.', 'שינוי תמונת פרופיל', 'JPG, PNG או WebP · עד 5 MB', 'עוקבים', 'במעקב', 'שמירת שינויים', 'שומר…', 'ביטול שינויים', 'יש לך שינויים שלא נשמרו.', 'השינויים נשמרו.', 'לא ניתן לשמור את השינויים. נסו שוב.', 'שגיאה', 'הצלחה', 'יש להזין שם באורך 1–200 תווים.', 'יש להזין כתובת דואר אלקטרוני תקינה.', 'יש להשתמש בלפחות 8 תווים ולא יותר מ־72 בתים.', 'תמונת הפרופיל עודכנה.', 'לא ניתן להעלות את התמונה. נסו שוב.', 'התראות', 'בחירה אם לקבל התראות בדפדפן הזה.', 'הדפדפן הזה אינו תומך בהתראות דחיפה.', 'חסומות', 'פעילות', 'כבויות', 'הפעלת התראות', 'כיבוי התראות', 'שליחת בדיקה', 'יש לאפשר התראות עבור האתר בהגדרות הדפדפן ואז לטעון מחדש את הדף.'],
};

export function getProfileSettingsCopy(language = 'en', translations?: Readonly<Record<string, string>>): ProfileSettingsCopy {
  const locale = language.toLowerCase().split('-')[0];
  const row = rows[locale];
  return Object.fromEntries(keys.map((key, index) => {
    const fallback = row?.[index] || english[key];
    const value = translations?.[`profile_settings_${key}`]?.trim();
    return [key, value && !(locale !== 'en' && value === english[key]) ? value : fallback];
  })) as ProfileSettingsCopy;
}

export const profileSettingsCopyCoverage = Object.fromEntries([
  ['en', keys.length], ...Object.entries(rows).map(([language, values]) => [language, values.length]),
]);
