const english = {
  back: 'All listeners', profile: 'Public profile', follow: 'Follow', following: 'Following', unfollow: 'Unfollow',
  share: 'Share profile', copy: 'Copy link', copied: 'Profile link copied', copyFailed: 'Could not copy the link. Please try again.',
  followers: 'Followers', favorites: 'Favorite stations', joined: 'Member since', edit: 'Edit profile',
  unavailable: 'Profile unavailable', unavailableBody: 'This profile is private or no longer available.',
  error: 'Could not load this profile', errorBody: 'Please check your connection and try again.', retry: 'Try again', loading: 'Loading profile…',
  empty: 'No favorite stations yet', emptyBody: 'This listener has not shared any favorite stations yet.', discover: 'Explore stations',
  more: 'Load more stations', moreError: 'Could not load more stations.', favoritesPrivate: 'These favorites are private.',
  followed: 'You are now following this listener.', unfollowed: 'You are no longer following this listener.', followFailed: 'Could not update your follow. Please try again.',
  anonymous: 'Listener', loadingMore: 'Loading stations…',
};

type LabelKey = keyof typeof english;
type Labels = Record<LabelKey, string>;
const keys = Object.keys(english) as LabelKey[];

// Keep current-locale fallbacks here: the global translator falls through to
// English before considering a caller's fallback when a dictionary is partial.
const localized: Record<string, string[]> = {
  de: ['Alle Hörer', 'Öffentliches Profil', 'Folgen', 'Gefolgt', 'Nicht mehr folgen', 'Profil teilen', 'Link kopieren', 'Profillink kopiert', 'Der Link konnte nicht kopiert werden. Bitte versuche es erneut.', 'Follower', 'Lieblingssender', 'Mitglied seit', 'Profil bearbeiten', 'Profil nicht verfügbar', 'Dieses Profil ist privat oder nicht mehr verfügbar.', 'Profil konnte nicht geladen werden', 'Prüfe deine Verbindung und versuche es erneut.', 'Erneut versuchen', 'Profil wird geladen…', 'Noch keine Lieblingssender', 'Dieser Hörer hat noch keine Lieblingssender geteilt.', 'Sender entdecken', 'Weitere Sender laden', 'Weitere Sender konnten nicht geladen werden.', 'Diese Favoriten sind privat.', 'Du folgst diesem Hörer jetzt.', 'Du folgst diesem Hörer nicht mehr.', 'Die Änderung konnte nicht gespeichert werden. Bitte versuche es erneut.', 'Hörer', 'Sender werden geladen…'],
  tr: ['Tüm dinleyiciler', 'Herkese açık profil', 'Takip et', 'Takip ediliyor', 'Takibi bırak', 'Profili paylaş', 'Bağlantıyı kopyala', 'Profil bağlantısı kopyalandı', 'Bağlantı kopyalanamadı. Lütfen tekrar dene.', 'Takipçiler', 'Favori istasyonlar', 'Katılma tarihi', 'Profili düzenle', 'Profil kullanılamıyor', 'Bu profil gizli veya artık kullanılamıyor.', 'Profil yüklenemedi', 'Bağlantını kontrol edip tekrar dene.', 'Tekrar dene', 'Profil yükleniyor…', 'Henüz favori istasyon yok', 'Bu dinleyici henüz favori istasyon paylaşmadı.', 'İstasyonları keşfet', 'Daha fazla istasyon yükle', 'Diğer istasyonlar yüklenemedi.', 'Bu favoriler gizli.', 'Bu dinleyiciyi artık takip ediyorsun.', 'Bu dinleyiciyi takip etmeyi bıraktın.', 'Takip durumu güncellenemedi. Lütfen tekrar dene.', 'Dinleyici', 'İstasyonlar yükleniyor…'],
  es: ['Todos los oyentes', 'Perfil público', 'Seguir', 'Siguiendo', 'Dejar de seguir', 'Compartir perfil', 'Copiar enlace', 'Enlace del perfil copiado', 'No se pudo copiar el enlace. Inténtalo de nuevo.', 'Seguidores', 'Emisoras favoritas', 'Miembro desde', 'Editar perfil', 'Perfil no disponible', 'Este perfil es privado o ya no está disponible.', 'No se pudo cargar el perfil', 'Comprueba tu conexión e inténtalo de nuevo.', 'Reintentar', 'Cargando perfil…', 'Aún no hay emisoras favoritas', 'Este oyente aún no ha compartido emisoras favoritas.', 'Explorar emisoras', 'Cargar más emisoras', 'No se pudieron cargar más emisoras.', 'Estos favoritos son privados.', 'Ahora sigues a este oyente.', 'Ya no sigues a este oyente.', 'No se pudo actualizar el seguimiento. Inténtalo de nuevo.', 'Oyente', 'Cargando emisoras…'],
  fr: ['Tous les auditeurs', 'Profil public', 'Suivre', 'Abonné', 'Ne plus suivre', 'Partager le profil', 'Copier le lien', 'Lien du profil copié', 'Impossible de copier le lien. Réessayez.', 'Abonnés', 'Stations favorites', 'Membre depuis', 'Modifier le profil', 'Profil indisponible', 'Ce profil est privé ou n’est plus disponible.', 'Impossible de charger le profil', 'Vérifiez votre connexion et réessayez.', 'Réessayer', 'Chargement du profil…', 'Aucune station favorite pour le moment', 'Cet auditeur n’a pas encore partagé de stations favorites.', 'Explorer les stations', 'Charger plus de stations', 'Impossible de charger plus de stations.', 'Ces favoris sont privés.', 'Vous suivez désormais cet auditeur.', 'Vous ne suivez plus cet auditeur.', 'Impossible de modifier l’abonnement. Réessayez.', 'Auditeur', 'Chargement des stations…'],
  pt: ['Todos os ouvintes', 'Perfil público', 'Seguir', 'Seguindo', 'Deixar de seguir', 'Compartilhar perfil', 'Copiar link', 'Link do perfil copiado', 'Não foi possível copiar o link. Tente novamente.', 'Seguidores', 'Estações favoritas', 'Membro desde', 'Editar perfil', 'Perfil indisponível', 'Este perfil é privado ou não está mais disponível.', 'Não foi possível carregar o perfil', 'Verifique sua conexão e tente novamente.', 'Tentar novamente', 'Carregando perfil…', 'Ainda não há estações favoritas', 'Este ouvinte ainda não compartilhou estações favoritas.', 'Explorar estações', 'Carregar mais estações', 'Não foi possível carregar mais estações.', 'Estes favoritos são privados.', 'Você está seguindo este ouvinte.', 'Você deixou de seguir este ouvinte.', 'Não foi possível atualizar o seguimento. Tente novamente.', 'Ouvinte', 'Carregando estações…'],
  it: ['Tutti gli ascoltatori', 'Profilo pubblico', 'Segui', 'Segui già', 'Non seguire più', 'Condividi profilo', 'Copia link', 'Link del profilo copiato', 'Impossibile copiare il link. Riprova.', 'Follower', 'Stazioni preferite', 'Iscritto dal', 'Modifica profilo', 'Profilo non disponibile', 'Questo profilo è privato o non è più disponibile.', 'Impossibile caricare il profilo', 'Controlla la connessione e riprova.', 'Riprova', 'Caricamento del profilo…', 'Ancora nessuna stazione preferita', 'Questo ascoltatore non ha ancora condiviso stazioni preferite.', 'Esplora le stazioni', 'Carica altre stazioni', 'Impossibile caricare altre stazioni.', 'Questi preferiti sono privati.', 'Ora segui questo ascoltatore.', 'Non segui più questo ascoltatore.', 'Impossibile aggiornare il seguito. Riprova.', 'Ascoltatore', 'Caricamento delle stazioni…'],
  ru: ['Все слушатели', 'Открытый профиль', 'Подписаться', 'Вы подписаны', 'Отписаться', 'Поделиться профилем', 'Копировать ссылку', 'Ссылка на профиль скопирована', 'Не удалось скопировать ссылку. Попробуйте снова.', 'Подписчики', 'Избранные станции', 'Дата регистрации', 'Изменить профиль', 'Профиль недоступен', 'Этот профиль закрыт или больше недоступен.', 'Не удалось загрузить профиль', 'Проверьте подключение и попробуйте снова.', 'Повторить', 'Загрузка профиля…', 'Пока нет избранных станций', 'Этот слушатель ещё не поделился избранными станциями.', 'Найти станции', 'Загрузить ещё станции', 'Не удалось загрузить другие станции.', 'Эти избранные станции скрыты.', 'Вы подписались на этого слушателя.', 'Вы отписались от этого слушателя.', 'Не удалось изменить подписку. Попробуйте снова.', 'Слушатель', 'Загрузка станций…'],
  ar: ['كل المستمعين', 'ملف شخصي عام', 'متابعة', 'تتابعه', 'إلغاء المتابعة', 'مشاركة الملف', 'نسخ الرابط', 'تم نسخ رابط الملف', 'تعذر نسخ الرابط. حاول مرة أخرى.', 'المتابعون', 'المحطات المفضلة', 'عضو منذ', 'تعديل الملف', 'الملف غير متاح', 'هذا الملف خاص أو لم يعد متاحًا.', 'تعذر تحميل الملف', 'تحقق من اتصالك وحاول مرة أخرى.', 'حاول مرة أخرى', 'جارٍ تحميل الملف…', 'لا توجد محطات مفضلة بعد', 'لم يشارك هذا المستمع أي محطات مفضلة بعد.', 'استكشف المحطات', 'تحميل المزيد من المحطات', 'تعذر تحميل المزيد من المحطات.', 'هذه المفضلة خاصة.', 'أنت تتابع هذا المستمع الآن.', 'لقد ألغيت متابعة هذا المستمع.', 'تعذر تحديث المتابعة. حاول مرة أخرى.', 'مستمع', 'جارٍ تحميل المحطات…'],
  zh: ['所有听众', '公开个人资料', '关注', '已关注', '取消关注', '分享个人资料', '复制链接', '已复制个人资料链接', '无法复制链接，请重试。', '关注者', '收藏的电台', '加入时间', '编辑个人资料', '个人资料不可用', '此个人资料已设为私密或不再可用。', '无法加载个人资料', '请检查网络连接后重试。', '重试', '正在加载个人资料…', '暂无收藏的电台', '这位听众尚未分享收藏的电台。', '探索电台', '加载更多电台', '无法加载更多电台。', '这些收藏已设为私密。', '你已关注这位听众。', '你已取消关注这位听众。', '无法更新关注状态，请重试。', '听众', '正在加载电台…'],
  ja: ['すべてのリスナー', '公開プロフィール', 'フォロー', 'フォロー中', 'フォロー解除', 'プロフィールを共有', 'リンクをコピー', 'プロフィールのリンクをコピーしました', 'リンクをコピーできませんでした。もう一度お試しください。', 'フォロワー', 'お気に入りの放送局', '登録日', 'プロフィールを編集', 'プロフィールを表示できません', 'このプロフィールは非公開か、現在利用できません。', 'プロフィールを読み込めませんでした', '接続を確認して、もう一度お試しください。', '再試行', 'プロフィールを読み込み中…', 'お気に入りの放送局はまだありません', 'このリスナーはまだお気に入りの放送局を共有していません。', '放送局を探す', '放送局をもっと読み込む', '追加の放送局を読み込めませんでした。', 'このお気に入りは非公開です。', 'このリスナーをフォローしました。', 'このリスナーのフォローを解除しました。', 'フォロー状態を更新できませんでした。もう一度お試しください。', 'リスナー', '放送局を読み込み中…'],
  ko: ['모든 청취자', '공개 프로필', '팔로우', '팔로우 중', '팔로우 취소', '프로필 공유', '링크 복사', '프로필 링크가 복사되었습니다', '링크를 복사할 수 없습니다. 다시 시도하세요.', '팔로워', '즐겨찾는 방송국', '가입일', '프로필 수정', '프로필을 볼 수 없습니다', '이 프로필은 비공개이거나 더 이상 사용할 수 없습니다.', '프로필을 불러올 수 없습니다', '연결을 확인하고 다시 시도하세요.', '다시 시도', '프로필 불러오는 중…', '아직 즐겨찾는 방송국이 없습니다', '이 청취자는 아직 즐겨찾는 방송국을 공유하지 않았습니다.', '방송국 둘러보기', '방송국 더 불러오기', '방송국을 더 불러올 수 없습니다.', '이 즐겨찾기는 비공개입니다.', '이 청취자를 팔로우합니다.', '이 청취자의 팔로우를 취소했습니다.', '팔로우 상태를 변경할 수 없습니다. 다시 시도하세요.', '청취자', '방송국 불러오는 중…'],
  hi: ['सभी श्रोता', 'सार्वजनिक प्रोफ़ाइल', 'फ़ॉलो करें', 'फ़ॉलो कर रहे हैं', 'अनफ़ॉलो करें', 'प्रोफ़ाइल साझा करें', 'लिंक कॉपी करें', 'प्रोफ़ाइल लिंक कॉपी हो गया', 'लिंक कॉपी नहीं हो सका। फिर से कोशिश करें।', 'फ़ॉलोअर', 'पसंदीदा स्टेशन', 'सदस्यता की तारीख', 'प्रोफ़ाइल संपादित करें', 'प्रोफ़ाइल उपलब्ध नहीं है', 'यह प्रोफ़ाइल निजी है या अब उपलब्ध नहीं है।', 'प्रोफ़ाइल लोड नहीं हो सकी', 'अपना कनेक्शन जाँचें और फिर से कोशिश करें।', 'फिर से कोशिश करें', 'प्रोफ़ाइल लोड हो रही है…', 'अभी कोई पसंदीदा स्टेशन नहीं है', 'इस श्रोता ने अभी तक कोई पसंदीदा स्टेशन साझा नहीं किया है।', 'स्टेशन खोजें', 'और स्टेशन लोड करें', 'और स्टेशन लोड नहीं हो सके।', 'ये पसंदीदा निजी हैं।', 'अब आप इस श्रोता को फ़ॉलो कर रहे हैं।', 'आपने इस श्रोता को अनफ़ॉलो कर दिया है।', 'फ़ॉलो स्थिति अपडेट नहीं हो सकी। फिर से कोशिश करें।', 'श्रोता', 'स्टेशन लोड हो रहे हैं…'],
  he: ['כל המאזינים', 'פרופיל ציבורי', 'עקוב', 'במעקב', 'הפסק לעקוב', 'שתף פרופיל', 'העתק קישור', 'הקישור לפרופיל הועתק', 'לא ניתן להעתיק את הקישור. נסה שוב.', 'עוקבים', 'תחנות מועדפות', 'חבר מאז', 'ערוך פרופיל', 'הפרופיל אינו זמין', 'הפרופיל הזה פרטי או אינו זמין עוד.', 'לא ניתן לטעון את הפרופיל', 'בדוק את החיבור ונסה שוב.', 'נסה שוב', 'טוען פרופיל…', 'עדיין אין תחנות מועדפות', 'המאזין הזה עדיין לא שיתף תחנות מועדפות.', 'גלה תחנות', 'טען תחנות נוספות', 'לא ניתן לטעון תחנות נוספות.', 'המועדפים האלה פרטיים.', 'כעת אתה עוקב אחר המאזין הזה.', 'הפסקת לעקוב אחר המאזין הזה.', 'לא ניתן לעדכן את המעקב. נסה שוב.', 'מאזין', 'טוען תחנות…'],
};

export function publicProfileLabels(language: string, translations?: Readonly<Record<string, string>>): Labels {
  const locale = language.toLowerCase().split('-')[0];
  return Object.fromEntries(keys.map((key, index) => {
    const translated = translations?.[`public_profile_${key}`]?.trim();
    return [key, translated || localized[locale]?.[index] || english[key]];
  })) as Labels;
}

export function profileNumber(value: unknown, language: string): string {
  return typeof value === 'number' && Number.isFinite(value) && value >= 0
    ? new Intl.NumberFormat(language).format(Math.floor(value)) : '—';
}

export function profileJoinedDate(value: string | undefined, language: string): string {
  const date = value ? new Date(value) : null;
  return date && Number.isFinite(date.getTime())
    ? date.toLocaleDateString(language, { month: 'short', day: 'numeric', year: 'numeric' }) : '—';
}
