// Critical billing states must stay understandable even if the remote dictionary
// is unavailable. Order: unavailable, checking, active, pending, retry, manage,
// continue, price, stream-ad disclaimer, sign in.
const copy: Record<string, readonly string[]> = {
  hi: ['भुगतान अस्थायी रूप से उपलब्ध नहीं है।', 'आपकी सदस्यता जाँची जा रही है…', 'आपकी सदस्यता सक्रिय है', 'आपकी सदस्यता की अभी पुष्टि नहीं हुई है। यदि आपने भुगतान किया है, तो कृपया प्रतीक्षा करें या सहायता से संपर्क करें। दोबारा भुगतान न करें।', 'फिर कोशिश करें', 'सदस्यता प्रबंधित करें', 'भुगतान जारी रखें', 'चेकआउट पर कीमत की पुष्टि होगी', 'रेडियो प्रसारण में शामिल विज्ञापन चल सकते हैं।', 'लॉग इन करें'],
  he: ['התשלומים אינם זמינים זמנית.', 'בודקים את המינוי שלך…', 'המינוי שלך פעיל', 'המינוי שלך טרם אושר. אם שילמת, יש להמתין או לפנות לתמיכה. אין לשלם שוב.', 'ניסיון נוסף', 'ניהול המינוי', 'המשך לתשלום', 'המחיר יאושר במעמד התשלום', 'פרסומות הכלולות בשידור הרדיו עשויות להמשיך להתנגן.', 'כניסה'],
  sv: ['Betalningar är tillfälligt otillgängliga.', 'Kontrollerar din prenumeration…', 'Din prenumeration är aktiv', 'Din prenumeration är inte bekräftad ännu. Om du har betalat, vänta eller kontakta supporten. Betala inte igen.', 'Försök igen', 'Hantera prenumeration', 'Fortsätt till betalning', 'Priset bekräftas i kassan', 'Reklam i radiosändningen kan fortfarande höras.', 'Logga in'],
  da: ['Betalinger er midlertidigt utilgængelige.', 'Kontrollerer dit abonnement…', 'Dit abonnement er aktivt', 'Dit abonnement er endnu ikke bekræftet. Hvis du har betalt, vent eller kontakt support. Betal ikke igen.', 'Prøv igen', 'Administrer abonnement', 'Fortsæt til betaling', 'Prisen bekræftes ved betaling', 'Reklamer i radioudsendelsen kan stadig høres.', 'Log ind'],
  no: ['Betalinger er midlertidig utilgjengelige.', 'Kontrollerer abonnementet ditt…', 'Abonnementet ditt er aktivt', 'Abonnementet ditt er ikke bekreftet ennå. Hvis du har betalt, vent eller kontakt brukerstøtte. Ikke betal på nytt.', 'Prøv igjen', 'Administrer abonnement', 'Fortsett til betaling', 'Prisen bekreftes i kassen', 'Reklame i radiosendingen kan fortsatt høres.', 'Logg inn'],
  en: ['Payments are temporarily unavailable.', 'Checking your subscription…', 'Your subscription is active', 'Your subscription is not yet confirmed. If you paid, please wait or contact support. Do not pay again.', 'Try again', 'Manage subscription', 'Continue to payment', 'Price confirmed at checkout', 'Ads included in the radio broadcast may still play.', 'Sign in'],
  de: ['Zahlungen sind vorübergehend nicht verfügbar.', 'Dein Abonnement wird geprüft…', 'Dein Abonnement ist aktiv', 'Dein Abonnement ist noch nicht bestätigt. Falls du bezahlt hast, warte bitte oder kontaktiere den Support. Bezahle nicht erneut.', 'Erneut versuchen', 'Abonnement verwalten', 'Weiter zur Zahlung', 'Preis wird an der Kasse bestätigt', 'Werbung im Radioprogramm kann weiterhin zu hören sein.', 'Anmelden'],
  tr: ['Ödemeler geçici olarak kullanılamıyor.', 'Aboneliğin kontrol ediliyor…', 'Aboneliğin aktif', 'Aboneliğin henüz doğrulanmadı. Ödeme yaptıysan lütfen bekle veya destekle iletişime geç. Tekrar ödeme yapma.', 'Tekrar dene', 'Aboneliği yönet', 'Ödemeye devam et', 'Fiyat ödeme ekranında doğrulanır', 'Radyo yayınının içindeki reklamlar devam edebilir.', 'Giriş yap'],
  fr: ['Les paiements sont temporairement indisponibles.', 'Vérification de votre abonnement…', 'Votre abonnement est actif', 'Votre abonnement n’est pas encore confirmé. Si vous avez payé, patientez ou contactez l’assistance. Ne payez pas à nouveau.', 'Réessayer', 'Gérer l’abonnement', 'Passer au paiement', 'Prix confirmé lors du paiement', 'Les publicités diffusées par la radio peuvent rester audibles.', 'Se connecter'],
  es: ['Los pagos no están disponibles temporalmente.', 'Comprobando tu suscripción…', 'Tu suscripción está activa', 'Tu suscripción aún no está confirmada. Si has pagado, espera o contacta con soporte. No vuelvas a pagar.', 'Reintentar', 'Gestionar suscripción', 'Continuar al pago', 'Precio confirmado al pagar', 'Los anuncios de la emisión de radio pueden seguir sonando.', 'Iniciar sesión'],
  it: ['I pagamenti non sono temporaneamente disponibili.', 'Verifica del tuo abbonamento…', 'Il tuo abbonamento è attivo', 'Il tuo abbonamento non è ancora confermato. Se hai pagato, attendi o contatta l’assistenza. Non pagare di nuovo.', 'Riprova', 'Gestisci abbonamento', 'Continua al pagamento', 'Prezzo confermato al pagamento', 'La pubblicità nella trasmissione radio può rimanere.', 'Accedi'],
  pt: ['Os pagamentos estão temporariamente indisponíveis.', 'A verificar a sua subscrição…', 'A sua subscrição está ativa', 'A sua subscrição ainda não foi confirmada. Se pagou, aguarde ou contacte o suporte. Não pague novamente.', 'Tentar novamente', 'Gerir subscrição', 'Continuar para pagamento', 'Preço confirmado no pagamento', 'A publicidade na transmissão de rádio pode continuar.', 'Iniciar sessão'],
  nl: ['Betalingen zijn tijdelijk niet beschikbaar.', 'Je abonnement wordt gecontroleerd…', 'Je abonnement is actief', 'Je abonnement is nog niet bevestigd. Heb je betaald, wacht dan of neem contact op met support. Betaal niet opnieuw.', 'Opnieuw proberen', 'Abonnement beheren', 'Doorgaan naar betaling', 'Prijs bevestigd bij afrekenen', 'Reclame in de radio-uitzending kan hoorbaar blijven.', 'Inloggen'],
  pl: ['Płatności są tymczasowo niedostępne.', 'Sprawdzanie subskrypcji…', 'Twoja subskrypcja jest aktywna', 'Twoja subskrypcja nie została jeszcze potwierdzona. Jeśli zapłacono, poczekaj lub skontaktuj się z pomocą. Nie płać ponownie.', 'Spróbuj ponownie', 'Zarządzaj subskrypcją', 'Przejdź do płatności', 'Cena potwierdzana przy płatności', 'Reklamy w audycji radiowej mogą nadal być odtwarzane.', 'Zaloguj się'],
  ru: ['Платежи временно недоступны.', 'Проверяем подписку…', 'Ваша подписка активна', 'Подписка пока не подтверждена. Если вы оплатили, подождите или обратитесь в поддержку. Не платите повторно.', 'Повторить', 'Управление подпиской', 'Перейти к оплате', 'Цена подтверждается при оплате', 'Реклама в эфире радиостанции может сохраняться.', 'Войти'],
  ar: ['المدفوعات غير متاحة مؤقتًا.', 'جارٍ التحقق من اشتراكك…', 'اشتراكك نشط', 'لم يتم تأكيد اشتراكك بعد. إذا دفعت، يُرجى الانتظار أو الاتصال بالدعم. لا تدفع مرة أخرى.', 'إعادة المحاولة', 'إدارة الاشتراك', 'المتابعة إلى الدفع', 'يتم تأكيد السعر عند الدفع', 'قد تستمر الإعلانات ضمن البث الإذاعي.', 'تسجيل الدخول'],
  zh: ['付款暂时不可用。', '正在检查订阅…', '您的订阅已生效', '您的订阅尚未确认。如果已付款，请等待或联系支持。请勿重复付款。', '重试', '管理订阅', '继续付款', '价格将在结账时确认', '电台广播中的广告可能仍会播放。', '登录'],
  ja: ['現在お支払いをご利用いただけません。', 'サブスクリプションを確認中…', 'サブスクリプションは有効です', 'サブスクリプションはまだ確認されていません。お支払い済みの場合は、しばらく待つかサポートにご連絡ください。再度支払わないでください。', '再試行', 'サブスクリプションの管理', 'お支払いに進む', '価格は決済時に確定します', 'ラジオ放送内の広告は引き続き流れる場合があります。', 'ログイン'],
  ko: ['결제를 일시적으로 사용할 수 없습니다.', '구독 확인 중…', '구독이 활성화되었습니다', '아직 구독이 확인되지 않았습니다. 결제했다면 기다리거나 지원팀에 문의하세요. 다시 결제하지 마세요.', '다시 시도', '구독 관리', '결제 계속하기', '가격은 결제 시 확정됩니다', '라디오 방송에 포함된 광고는 계속 재생될 수 있습니다.', '로그인'],
};
export function subscriptionCopy(language: string) {
  const [unavailable, checking, active, pending, retry, manage, continuePayment, price, broadcastAds, signIn] = copy[language] || copy.en;
  return { unavailable, checking, active, pending, retry, manage, continuePayment, price, broadcastAds, signIn };
}
