const keys = ['community','title','subtitle','search','clear','sort','newest','oldest','most','least','more','loading','empty','reset','error','retry','listener'] as const;
const rows: Record<string, readonly string[]> = {
  en: ['Community','Find your radio people','Discover listeners and the stations they love.','Search listeners','Clear search','Sort listeners','Newest members','Oldest members','Most favorites','Fewest favorites','Load more listeners','Loading listeners…','No listeners match your search.','Clear filters','We could not load listeners. Please try again.','Try again','Listener'],
  de: ['Community','Entdecke deine Radio-Community','Finde Menschen und ihre Lieblingssender.','Benutzer suchen','Suche löschen','Benutzer sortieren','Neueste Mitglieder','Älteste Mitglieder','Meiste Favoriten','Wenigste Favoriten','Weitere Benutzer laden','Benutzer werden geladen…','Keine passenden Benutzer gefunden.','Filter zurücksetzen','Benutzer konnten nicht geladen werden. Bitte versuche es erneut.','Erneut versuchen','Hörer'],
  tr: ['Topluluk','Radyo tutkunlarıyla tanış','Dinleyicileri ve sevdikleri radyoları keşfet.','Kullanıcı ara','Aramayı temizle','Kullanıcıları sırala','En yeni üyeler','En eski üyeler','En çok favori','En az favori','Daha fazla kullanıcı','Kullanıcılar yükleniyor…','Aramana uygun kullanıcı bulunamadı.','Filtreleri temizle','Kullanıcılar yüklenemedi. Lütfen tekrar dene.','Tekrar dene','Dinleyici'],
  es: ['Comunidad','Encuentra tu comunidad de radio','Descubre oyentes y sus emisoras favoritas.','Buscar usuarios','Borrar búsqueda','Ordenar usuarios','Miembros recientes','Miembros antiguos','Más favoritos','Menos favoritos','Cargar más usuarios','Cargando usuarios…','No se encontraron usuarios.','Borrar filtros','No se pudieron cargar los usuarios.','Reintentar','Oyente'],
  fr: ['Communauté','Rencontrez votre communauté radio','Découvrez les auditeurs et leurs stations préférées.','Rechercher des utilisateurs','Effacer la recherche','Trier les utilisateurs','Membres récents','Membres anciens','Plus de favoris','Moins de favoris','Afficher plus d’utilisateurs','Chargement des utilisateurs…','Aucun utilisateur trouvé.','Effacer les filtres','Impossible de charger les utilisateurs.','Réessayer','Auditeur'],
  pt: ['Comunidade','Encontre sua comunidade de rádio','Descubra ouvintes e suas rádios favoritas.','Buscar usuários','Limpar busca','Ordenar usuários','Membros recentes','Membros antigos','Mais favoritos','Menos favoritos','Carregar mais usuários','Carregando usuários…','Nenhum usuário encontrado.','Limpar filtros','Não foi possível carregar os usuários.','Tentar novamente','Ouvinte'],
  it: ['Community','Trova la tua comunità radio','Scopri gli ascoltatori e le loro stazioni preferite.','Cerca utenti','Cancella ricerca','Ordina utenti','Membri più recenti','Membri meno recenti','Più preferiti','Meno preferiti','Carica altri utenti','Caricamento utenti…','Nessun utente trovato.','Cancella filtri','Impossibile caricare gli utenti.','Riprova','Ascoltatore'],
  ru: ['Сообщество','Найдите своё радио-сообщество','Откройте слушателей и их любимые станции.','Поиск пользователей','Очистить поиск','Сортировка пользователей','Новые участники','Старые участники','Больше избранного','Меньше избранного','Загрузить ещё','Загрузка пользователей…','Пользователи не найдены.','Сбросить фильтры','Не удалось загрузить пользователей.','Повторить','Слушатель'],
  ar: ['المجتمع','اكتشف مجتمع عشاق الراديو','تعرّف على المستمعين ومحطاتهم المفضلة.','البحث عن مستخدمين','مسح البحث','ترتيب المستخدمين','أحدث الأعضاء','أقدم الأعضاء','الأكثر تفضيلاً','الأقل تفضيلاً','تحميل المزيد','جارٍ تحميل المستخدمين…','لم يتم العثور على مستخدمين.','مسح المرشحات','تعذر تحميل المستخدمين.','إعادة المحاولة','مستمع'],
  zh: ['社区','发现你的电台同好','认识听众，发现他们喜爱的电台。','搜索用户','清除搜索','用户排序','最新成员','最早成员','收藏最多','收藏最少','加载更多用户','正在加载用户…','未找到匹配用户。','清除筛选','无法加载用户，请重试。','重试','听众'],
  ja: ['コミュニティ','ラジオ仲間を見つけよう','リスナーとお気に入りの放送局を見つけましょう。','ユーザーを検索','検索をクリア','ユーザーの並び順','新しいメンバー','以前からのメンバー','お気に入りが多い順','お気に入りが少ない順','さらに表示','ユーザーを読み込み中…','ユーザーが見つかりません。','フィルターをクリア','ユーザーを読み込めませんでした。','再試行','リスナー'],
  ko: ['커뮤니티','라디오 친구를 만나세요','청취자와 그들이 좋아하는 방송국을 찾아보세요.','사용자 검색','검색 지우기','사용자 정렬','최신 회원','오래된 회원','즐겨찾기 많은 순','즐겨찾기 적은 순','더 불러오기','사용자 불러오는 중…','검색 결과가 없습니다.','필터 초기화','사용자를 불러올 수 없습니다.','다시 시도','청취자'],
  hi: ['समुदाय','अपने रेडियो साथी खोजें','श्रोताओं और उनके पसंदीदा स्टेशन खोजें।','उपयोगकर्ता खोजें','खोज साफ़ करें','उपयोगकर्ता क्रम','नए सदस्य','पुराने सदस्य','सबसे अधिक पसंदीदा','सबसे कम पसंदीदा','और उपयोगकर्ता देखें','उपयोगकर्ता लोड हो रहे हैं…','कोई उपयोगकर्ता नहीं मिला।','फ़िल्टर हटाएँ','उपयोगकर्ता लोड नहीं हो सके।','फिर कोशिश करें','श्रोता'],
  he: ['קהילה','גלו את קהילת הרדיו שלכם','גלו מאזינים ואת התחנות שהם אוהבים.','חיפוש משתמשים','ניקוי החיפוש','מיון משתמשים','חברים חדשים','חברים ותיקים','הכי הרבה מועדפים','הכי מעט מועדפים','טעינת משתמשים נוספים','טוען משתמשים…','לא נמצאו משתמשים מתאימים.','ניקוי מסננים','לא ניתן לטעון משתמשים.','ניסיון חוזר','מאזין'],
};
export function usersDirectoryCopy(language: string) {
  const row = rows[language.split('-')[0]] || rows.en;
  return Object.fromEntries(keys.map((key,index) => [key,row[index]])) as Record<typeof keys[number],string>;
}
