[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.web"

[deploy]
startCommand = "node --max-old-space-size=2048 --max-semi-space-size=32 --expose-gc dist/index-web.js"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 5
