[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 5
