// URL translations for multilingual routing
// Auto-generated by scripts/generate-url-translations.ts
// Each language has a mapping of English path segments to translated segments

export interface UrlTranslations {
  [language: string]: {
    [englishPath: string]: string;
  };
}

// Database URL translations cache (loaded from MongoDB, overrides static translations)
// Forward map: "languageCode:englishPath" -> translatedPath
let databaseUrlTranslationsCache: Map<string, string> | null = null;

// Reverse map for inbound routing: "languageCode:translatedPath" -> englishPath
let databaseReverseUrlTranslationsCache: Map<string, string> | null = null;

// Database reverse URL translations cache (for translating back to English)
let databaseReverseTranslationsCache: Map<string, string> | null = null;

// URL translations for all supported languages
export const URL_TRANSLATIONS: UrlTranslations = {
  // Arabic URL translations (Latinized for URL compatibility)
  ar: {
    'about': 'an',
    'album': 'album',
    'applications': 'tatbiqat',
    'artist': 'fannan',
    'change-password': 'taghyir-kalimat-almurur',
    'contact': 'ittisal',
    'discover': 'iktishaf',
    'discover-music': 'iktishaf-almusiqa',
    'favorites': 'mufadalat',
    'feedback': 'mulahazat',
    'forgot-password': 'nasit-kalimat-almurur',
    'genres': 'anwaa',
    'login': 'login',
    'notifications': 'isharat',
    'pages': 'safahat',
    'privacy-policy': 'siyasat-alkhususiya',
    'profile': 'malaf-shakhsi',
    'radios': 'mahtat',
    'recommendations': 'tawsiyat',
    'records': 'sijilat',
    'regions': 'manatiq',
    'request-station': 'talab-mahta',
    'settings': 'aidadat',
    'signup': 'tasjil-dukul',
    'song': 'ughniya',
    'station': 'mahta',
    'stations': 'mahtat',
    'terms-and-conditions': 'alshurut-walahkam',
    'trending': 'raij',
    'users': 'mustakhdimin',
  },

  // Azerbaijani URL translations
  az: {
    'about': 'haqqinda',
    'album': 'albom',
    'applications': 'proqramlar',
    'artist': 'ifacı',
    'change-password': 'sifre-deyis',
    'contact': 'elaqe',
    'discover': 'kesf-et',
    'discover-music': 'musiqi-kesf-et',
    'favorites': 'sevimliler',
    'feedback': 'geribildirim',
    'forgot-password': 'sifre-unutduq',
    'genres': 'janrlar',
    'login': 'login',
    'notifications': 'bildirişlər',
    'pages': 'sahifeler',
    'privacy-policy': 'mesxuriyet-siyaseti',
    'profile': 'profil',
    'radios': 'radio',
    'recommendations': 'tavsiyeler',
    'records': 'qeydlər',
    'regions': 'regionlar',
    'request-station': 'istediq-stansiya',
    'settings': 'ayarlar',
    'signup': 'signup',
    'song': 'mahnı',
    'station': 'stansiya',
    'stations': 'stansiyalar',
    'terms-and-conditions': 'şertler-ve-şertler',
    'trending': 'trendler',
    'users': 'istifadəçilər',
  },

  // Bulgarian URL translations
  bg: {
    'about': 'za-nas',
    'album': 'albm',
    'applications': 'prilozheniya',
    'artist': 'izpalnitel',
    'change-password': 'promiana-parola',
    'contact': 'kontakti',
    'discover': 'otkri',
    'discover-music': 'otkri-muzika',
    'favorites': 'lyubimi',
    'feedback': 'obratna-vrska',
    'forgot-password': 'zabravena-parola',
    'genres': 'zhanroves',
    'login': 'login',
    'notifications': 'izvestiya',
    'pages': 'stranitsi',
    'privacy-policy': 'politika-za-poveritelnost',
    'profile': 'profil',
    'radios': 'radio',
    'recommendations': 'preporaki',
    'records': 'zapiski',
    'regions': 'regioni',
    'request-station': 'zayavka-stantsiya',
    'settings': 'nastroiki',
    'signup': 'signup',
    'song': 'pesen',
    'station': 'stantsiya',
    'stations': 'stantsii',
    'terms-and-conditions': 'usloviya-i-nakazaniya',
    'trending': 'trenirovki',
    'users': 'potrebiteli',
  },

  // German URL translations
  de: {
    'about': 'ueber',
    'album': 'album',
    'applications': 'anwendungen',
    'artist': 'kuenstler',
    'change-password': 'passwort-aendern',
    'contact': 'kontakt',
    'discover': 'entdecken',
    'discover-music': 'musik-entdecken',
    'favorites': 'favoriten',
    'feedback': 'feedback',
    'forgot-password': 'passwort-vergessen',
    'genres': 'genres',
    'login': 'login',
    'notifications': 'benachrichtigungen',
    'pages': 'seiten',
    'privacy-policy': 'datenschutz',
    'profile': 'profil',
    'radios': 'radios',
    'recommendations': 'empfehlungen',
    'records': 'aufnahmen',
    'regions': 'regionen',
    'request-station': 'sender-anfordern',
    'settings': 'einstellungen',
    'signup': 'signup',
    'song': 'lied',
    'station': 'sender',
    'stations': 'sender',
    'terms-and-conditions': 'agb',
    'trending': 'trending',
    'users': 'benutzer',
  },

  // Greek URL translations
  el: {
    'about': 'σχετικα',
    'album': 'αλμπουμ',
    'applications': 'εφαρμογες',
    'artist': 'καλλιτεχνης',
    'change-password': 'αλλαγη-κωδικου',
    'contact': 'επικοινωνια',
    'discover': 'ανακαλυψε',
    'discover-music': 'ανακαλυψε-μουσικη',
    'favorites': 'αγαπημενα',
    'feedback': 'ανατροφοδοτηση',
    'forgot-password': 'ξεχασα-κωδικο',
    'genres': 'ειδη',
    'login': 'login',
    'notifications': 'ειδοποιησεις',
    'pages': 'σελιδες',
    'privacy-policy': 'πολιτικη-απορρητου',
    'profile': 'προφιλ',
    'radios': 'ραδιοφωνα',
    'recommendations': 'προτασεις',
    'records': 'δισκοι',
    'regions': 'περιφερειες',
    'request-station': 'αιτημα-σταθμου',
    'settings': 'ρυθμισεις',
    'signup': 'signup',
    'song': 'τραγουδι',
    'station': 'σταθμος',
    'stations': 'σταθμοι',
    'terms-and-conditions': 'οροι-και-προϋποθεσεις',
    'trending': 'δημοφιλη',
    'users': 'χρηστες',
  },

  // Spanish URL translations
  es: {
    'about': 'acerca',
    'album': 'album',
    'applications': 'aplicaciones',
    'artist': 'artista',
    'change-password': 'cambiar-contrasena',
    'contact': 'contacto',
    'discover': 'descubrir',
    'discover-music': 'descubrir-musica',
    'favorites': 'favoritos',
    'feedback': 'comentarios',
    'forgot-password': 'olvidar-contrasena',
    'genres': 'generos',
    'login': 'login',
    'notifications': 'notificaciones',
    'pages': 'paginas',
    'privacy-policy': 'politica-de-privacidad',
    'profile': 'perfil',
    'radios': 'radios',
    'recommendations': 'recomendaciones',
    'records': 'registros',
    'regions': 'regiones',
    'request-station': 'solicitar-estacion',
    'settings': 'configuracion',
    'signup': 'signup',
    'song': 'cancion',
    'station': 'estacion',
    'stations': 'estaciones',
    'terms-and-conditions': 'terminos-y-condiciones',
    'trending': 'tendencias',
    'users': 'usuarios',
  },

  // Persian URL translations
  fa: {
    'about': 'darbare',
    'album': 'album',
    'applications': 'barnameha',
    'artist': 'artist',
    'change-password': 'taghir-password',
    'contact': 'ertebat',
    'discover': 'discover',
    'discover-music': 'discover-music',
    'favorites': 'alaveh-ha',
    'feedback': 'bazkhord',
    'forgot-password': 'faramoosh-kardan-password',
    'genres': 'genres',
    'login': 'login',
    'notifications': 'akhbar',
    'pages': 'safahat',
    'privacy-policy': 'siyasat-haye-hoshmandi',
    'profile': 'profil',
    'radios': 'radioha',
    'recommendations': 'pishnahad-ha',
    'records': 'sukhtah',
    'regions': 'manategh',
    'request-station': 'darkhast-station',
    'settings': 'nezam',
    'signup': 'signup',
    'song': 'sang',
    'station': 'station',
    'stations': 'stations',
    'terms-and-conditions': 'sharayet-va-movaghat',
    'trending': 'dargir',
    'users': 'karbaran',
  },

  // Finnish URL translations
  fi: {
    'about': 'tietoa',
    'album': 'albumi',
    'applications': 'sovellukset',
    'artist': 'artisti',
    'change-password': 'vaihda-salasana',
    'contact': 'yhteys',
    'discover': 'löydä',
    'discover-music': 'löydä-musiikkia',
    'favorites': 'suosikit',
    'feedback': 'palaute',
    'forgot-password': 'unohtunut-salasana',
    'genres': 'genret',
    'login': 'login',
    'notifications': 'ilmoitukset',
    'pages': 'sivut',
    'privacy-policy': 'tietosuojakäytäntö',
    'profile': 'profiili',
    'radios': 'radiot',
    'recommendations': 'suositukset',
    'records': 'levyt',
    'regions': 'alueet',
    'request-station': 'pyydä-asema',
    'settings': 'asetukset',
    'signup': 'rekisteröidy',
    'song': 'kappale',
    'station': 'asema',
    'stations': 'asemat',
    'terms-and-conditions': 'ehdot',
    'trending': 'trendaavat',
    'users': 'käyttäjät',
  },

  // French URL translations
  fr: {
    'about': 'a-propos',
    'album': 'album',
    'applications': 'applications',
    'artist': 'artiste',
    'change-password': 'changer-mot-de-passe',
    'contact': 'contact',
    'discover': 'decouvrir',
    'discover-music': 'decouvrir-musique',
    'favorites': 'favoris',
    'feedback': 'retour',
    'forgot-password': 'mot-de-passe-oublie',
    'genres': 'genres',
    'login': 'login',
    'notifications': 'notifications',
    'pages': 'pages',
    'privacy-policy': 'politique-de-confidentialite',
    'profile': 'profil',
    'radios': 'radios',
    'recommendations': 'recommandations',
    'records': 'enregistrements',
    'regions': 'regions',
    'request-station': 'demander-station',
    'settings': 'parametres',
    'signup': 'inscription',
    'song': 'chanson',
    'station': 'station',
    'stations': 'stations',
    'terms-and-conditions': 'conditions-generales',
    'trending': 'tendances',
    'users': 'utilisateurs',
  },

  // Hebrew URL translations (Latinized for URL compatibility)
  he: {
    'about': 'al-odot',
    'album': 'albom',
    'applications': 'yishumim',
    'artist': 'oman',
    'change-password': 'shaneh-sisma',
    'contact': 'tzor-kesher',
    'discover': 'galeh',
    'discover-music': 'galeh-musika',
    'favorites': 'meoafim',
    'feedback': 'mashuv',
    'forgot-password': 'shachachti-sisma',
    'genres': 'zhanrim',
    'login': 'login',
    'notifications': 'hatraot',
    'pages': 'dapim',
    'privacy-policy': 'mediniyut-prati yut',
    'profile': 'profil',
    'radios': 'radio',
    'recommendations': 'hamlatzot',
    'records': 'taklitim',
    'regions': 'ezurim',
    'request-station': 'bakashat-tachana',
    'settings': 'hagdarot',
    'signup': 'harsama',
    'song': 'shir',
    'station': 'tachana',
    'stations': 'tachanot',
    'terms-and-conditions': 'tnaim-vehagbalot',
    'trending': 'trendim',
    'users': 'mishtamshim',
  },

  // Hindi URL translations (Latinized for URL compatibility)
  hi: {
    'about': 'ke-bare-mein',
    'album': 'album',
    'applications': 'anuprayog',
    'artist': 'kalakar',
    'change-password': 'password-parivartan',
    'contact': 'sampark',
    'discover': 'khojen',
    'discover-music': 'sangeet-khojen',
    'favorites': 'pasandida',
    'feedback': 'pratikriya',
    'forgot-password': 'password-bhul-gaye',
    'genres': 'shailiyan',
    'login': 'login',
    'notifications': 'soochnaen',
    'pages': 'pristh',
    'privacy-policy': 'gopaniyata-niti',
    'profile': 'profile',
    'radios': 'radio',
    'recommendations': 'sifarishen',
    'records': 'record',
    'regions': 'kshetra',
    'request-station': 'anurodh-station',
    'settings': 'settings',
    'signup': 'signup',
    'song': 'gana',
    'station': 'station',
    'stations': 'stations',
    'terms-and-conditions': 'niyam-aur-sharten',
    'trending': 'pravrittiya',
    'users': 'upyogkarta',
  },

  // Croatian URL translations
  hr: {
    'about': 'o-nama',
    'album': 'album',
    'applications': 'aplikacije',
    'artist': 'umjetnik',
    'change-password': 'promijeni-lozinku',
    'contact': 'kontakt',
    'discover': 'otkrij',
    'discover-music': 'otkrij-glazbu',
    'favorites': 'omiljeni',
    'feedback': 'povratne-informacije',
    'forgot-password': 'zaboravljena-lozinka',
    'genres': 'žanrovi',
    'login': 'login',
    'notifications': 'obavijesti',
    'pages': 'stranice',
    'privacy-policy': 'pravila-o-privatnosti',
    'profile': 'profil',
    'radios': 'radio',
    'recommendations': 'preporuke',
    'records': 'zapisi',
    'regions': 'regije',
    'request-station': 'zatraži-stanicu',
    'settings': 'postavke',
    'signup': 'signup',
    'song': 'pjesma',
    'station': 'stanica',
    'stations': 'stanice',
    'terms-and-conditions': 'uvjeti-i-odredbe',
    'trending': 'trending',
    'users': 'korisnici',
  },

  // Hungarian URL translations
  hu: {
    'about': 'rolunk',
    'album': 'album',
    'applications': 'alkalmazasok',
    'artist': 'muvész',
    'change-password': 'jelszo-valtoztatas',
    'contact': 'kapcsolat',
    'discover': 'felfedez',
    'discover-music': 'zenek-felfedezese',
    'favorites': 'kedvencek',
    'feedback': 'visszajelzes',
    'forgot-password': 'elfelejtett-jelszo',
    'genres': 'mufajok',
    'login': 'login',
    'notifications': 'ertesitesek',
    'pages': 'oldalak',
    'privacy-policy': 'adatvedelmi-tajekoztato',
    'profile': 'profil',
    'radios': 'radios',
    'recommendations': 'ajanlasok',
    'records': 'felvetelek',
    'regions': 'teruletek',
    'request-station': 'keres-radio',
    'settings': 'beallitasok',
    'signup': 'regisztracio',
    'song': 'dal',
    'station': 'radio',
    'stations': 'radios',
    'terms-and-conditions': 'felhasznalasi-feltetelek',
    'trending': 'trending',
    'users': 'felhasznalok',
  },

  // Armenian URL translations
  hy: {
    'about': 'մասին',
    'album': 'ալբոմ',
    'applications': 'հայտարարություններ',
    'artist': 'արվեստագետ',
    'change-password': 'փոխել-գաղտնաբառը',
    'contact': 'կապ',
    'discover': 'բացահայտել',
    'discover-music': 'բացահայտել-երաժշտություն',
    'favorites': 'սիրվածներ',
    'feedback': 'մեկնաբանություն',
    'forgot-password': 'մոռացել-գաղտնաբառը',
    'genres': 'ժանրեր',
    'login': 'login',
    'notifications': 'ծանուցումներ',
    'pages': 'էջեր',
    'privacy-policy': 'հետաքրքրությունների-քաղաքականություն',
    'profile': 'պրոֆիլ',
    'radios': 'ռադիոներ',
    'recommendations': 'առաջարկություններ',
    'records': 'ռեկորդներ',
    'regions': 'տարածքներ',
    'request-station': 'խնդրել-ստացիա',
    'settings': 'կարգավորումներ',
    'signup': 'signup',
    'song': 'երգ',
    'station': 'ստացիա',
    'stations': 'ստացիաներ',
    'terms-and-conditions': 'պայմաններ-և-պայմաններ',
    'trending': 'հանրաճանաչ',
    'users': 'օգտագործողներ',
  },

  // Indonesian URL translations
  id: {
    'about': 'tentang',
    'album': 'album',
    'applications': 'aplikasi',
    'artist': 'artis',
    'change-password': 'ganti-sandi',
    'contact': 'kontak',
    'discover': 'temukan',
    'discover-music': 'temukan-musik',
    'favorites': 'favorit',
    'feedback': 'umpan-balik',
    'forgot-password': 'lupa-sandi',
    'genres': 'genre',
    'login': 'login',
    'notifications': 'notifikasi',
    'pages': 'halaman',
    'privacy-policy': 'kebijakan-privasi',
    'profile': 'profil',
    'radios': 'radio',
    'recommendations': 'rekomendasi',
    'records': 'rekaman',
    'regions': 'wilayah',
    'request-station': 'permintaan-stasiun',
    'settings': 'pengaturan',
    'signup': 'daftar',
    'song': 'lagu',
    'station': 'stasiun',
    'stations': 'stasiun',
    'terms-and-conditions': 'syarat-dan-ketentuan',
    'trending': 'trending',
    'users': 'pengguna',
  },

  // Italian URL translations
  it: {
    'about': 'chi-siamo',
    'album': 'album',
    'applications': 'applicazioni',
    'artist': 'artista',
    'change-password': 'cambia-password',
    'contact': 'contatto',
    'discover': 'scopri',
    'discover-music': 'scopri-musica',
    'favorites': 'preferiti',
    'feedback': 'feedback',
    'forgot-password': 'password-dimenticata',
    'genres': 'generi',
    'login': 'login',
    'notifications': 'notifiche',
    'pages': 'pagine',
    'privacy-policy': 'politica-sulla-privacy',
    'profile': 'profilo',
    'radios': 'radio',
    'recommendations': 'raccomandazioni',
    'records': 'dischi',
    'regions': 'regioni',
    'request-station': 'richiesta-stazione',
    'settings': 'impostazioni',
    'signup': 'signup',
    'song': 'canzone',
    'station': 'stazione',
    'stations': 'stazioni',
    'terms-and-conditions': 'termini-e-condizioni',
    'trending': 'tendenze',
    'users': 'utenti',
  },

  // Japanese URL translations
  ja: {
    'about': '約',
    'album': 'アルバム',
    'applications': 'アプリ',
    'artist': 'アーティスト',
    'change-password': 'パスワード変更',
    'contact': 'お問い合わせ',
    'discover': '発見',
    'discover-music': '音楽発見',
    'favorites': 'お気に入り',
    'feedback': 'フィードバック',
    'forgot-password': 'パスワードを忘れた',
    'genres': 'ジャンル',
    'login': 'login',
    'notifications': '通知',
    'pages': 'ページ',
    'privacy-policy': 'プライバシーポリシー',
    'profile': 'プロフィール',
    'radios': 'ラジオ',
    'recommendations': 'おすすめ',
    'records': 'レコード',
    'regions': '地域',
    'request-station': 'リクエストステーション',
    'settings': '設定',
    'signup': 'signup',
    'song': '曲',
    'station': 'ステーション',
    'stations': 'ステーション',
    'terms-and-conditions': '利用規約',
    'trending': 'トレンド',
    'users': 'ユーザー',
  },

  // Korean URL translations
  ko: {
    'about': '소개',
    'album': '앨범',
    'applications': '애플리케이션',
    'artist': '아티스트',
    'change-password': '비밀번호-변경',
    'contact': '연락처',
    'discover': '발견',
    'discover-music': '음악-발견',
    'favorites': '즐겨찾기',
    'feedback': '피드백',
    'forgot-password': '비밀번호-찾기',
    'genres': '장르',
    'login': 'login',
    'notifications': '알림',
    'pages': '페이지',
    'privacy-policy': '개인정보-정책',
    'profile': '프로필',
    'radios': '라디오',
    'recommendations': '추천',
    'records': '레코드',
    'regions': '지역',
    'request-station': '요청-스테이션',
    'settings': '설정',
    'signup': 'signup',
    'song': '노래',
    'station': '스테이션',
    'stations': '스테이션',
    'terms-and-conditions': '이용약관',
    'trending': '트렌딩',
    'users': '사용자',
  },

  // Malay URL translations
  ms: {
    'about': 'tentang',
    'album': 'album',
    'applications': 'aplikasi',
    'artist': 'artis',
    'change-password': 'tukar-katalaluan',
    'contact': 'hubungi',
    'discover': 'temui',
    'discover-music': 'temui-muzik',
    'favorites': 'favorit',
    'feedback': 'maklumbalas',
    'forgot-password': 'lupa-katalaluan',
    'genres': 'genre',
    'login': 'login',
    'notifications': 'notifikasi',
    'pages': 'halaman',
    'privacy-policy': 'dasar-keselamatan',
    'profile': 'profil',
    'radios': 'radio',
    'recommendations': 'saran',
    'records': 'rekod',
    'regions': 'wilayah',
    'request-station': 'permintaan-stesen',
    'settings': 'tetapan',
    'signup': 'daftar',
    'song': 'lagu',
    'station': 'stesen',
    'stations': 'stesen',
    'terms-and-conditions': 'terma-dan-syarat',
    'trending': 'trending',
    'users': 'pengguna',
  },

  // Dutch URL translations
  nl: {
    'about': 'over',
    'album': 'album',
    'applications': 'toepassingen',
    'artist': 'artiest',
    'change-password': 'wachtwoord-wijzigen',
    'contact': 'contact',
    'discover': 'ontdek',
    'discover-music': 'ontdek-muziek',
    'favorites': 'favorieten',
    'feedback': 'feedback',
    'forgot-password': 'wachtwoord-vergeten',
    'genres': 'genres',
    'login': 'login',
    'notifications': 'meldingen',
    'pages': 'pagina\'s',
    'privacy-policy': 'privacy-beleid',
    'profile': 'profiel',
    'radios': 'radio\'s',
    'recommendations': 'aanbevelingen',
    'records': 'records',
    'regions': 'regio\'s',
    'request-station': 'verzoek-station',
    'settings': 'instellingen',
    'signup': 'aanmelden',
    'song': 'nummer',
    'station': 'station',
    'stations': 'stations',
    'terms-and-conditions': 'voorwaarden',
    'trending': 'trending',
    'users': 'gebruikers',
  },

  // Norwegian URL translations
  no: {
    'about': 'om',
    'album': 'album',
    'applications': 'applikasjoner',
    'artist': 'artist',
    'change-password': 'endre-passord',
    'contact': 'kontakt',
    'discover': 'oppdag',
    'discover-music': 'oppdag-musikk',
    'favorites': 'favoritter',
    'feedback': 'tilbakemelding',
    'forgot-password': 'glemt-passord',
    'genres': 'sjangre',
    'login': 'login',
    'notifications': 'varsler',
    'pages': 'sider',
    'privacy-policy': 'personvernerklæring',
    'profile': 'profil',
    'radios': 'radioer',
    'recommendations': 'anbefalinger',
    'records': 'opptak',
    'regions': 'regioner',
    'request-station': 'forespørsel-stasjon',
    'settings': 'innstillinger',
    'signup': 'signup',
    'song': 'sang',
    'station': 'stasjon',
    'stations': 'stasjoner',
    'terms-and-conditions': 'vilkår-og-betingelser',
    'trending': 'trending',
    'users': 'brukere',
  },

  // Polish URL translations
  pl: {
    'about': 'o-nas',
    'album': 'album',
    'applications': 'aplikacje',
    'artist': 'artysta',
    'change-password': 'zmiana-hasla',
    'contact': 'kontakt',
    'discover': 'odkryj',
    'discover-music': 'odkryj-muzyke',
    'favorites': 'ulubione',
    'feedback': 'opinie',
    'forgot-password': 'zapomniane-haslo',
    'genres': 'gatunki',
    'login': 'login',
    'notifications': 'powiadomienia',
    'pages': 'strony',
    'privacy-policy': 'polityka-prywatnosci',
    'profile': 'profil',
    'radios': 'radia',
    'recommendations': 'polecane',
    'records': 'nagrania',
    'regions': 'regiony',
    'request-station': 'zglos-stacje',
    'settings': 'ustawienia',
    'signup': 'rejestracja',
    'song': 'piosenka',
    'station': 'stacja',
    'stations': 'stacje',
    'terms-and-conditions': 'regulamin',
    'trending': 'trendy',
    'users': 'uzytkownicy',
  },

  // Portuguese URL translations
  pt: {
    'about': 'sobre',
    'album': 'album',
    'applications': 'aplicativos',
    'artist': 'artista',
    'change-password': 'mudar-senha',
    'contact': 'contato',
    'discover': 'descobrir',
    'discover-music': 'descobrir-musica',
    'favorites': 'favoritos',
    'feedback': 'feedback',
    'forgot-password': 'esqueci-senha',
    'genres': 'generos',
    'login': 'login',
    'notifications': 'notificacoes',
    'pages': 'paginas',
    'privacy-policy': 'politica-de-privacidade',
    'profile': 'perfil',
    'radios': 'radios',
    'recommendations': 'recomendacoes',
    'records': 'registros',
    'regions': 'regioes',
    'request-station': 'solicitar-estacao',
    'settings': 'configuracoes',
    'signup': 'cadastro',
    'song': 'musica',
    'station': 'estacao',
    'stations': 'estacoes',
    'terms-and-conditions': 'termos-e-condicoes',
    'trending': 'tendencias',
    'users': 'usuarios',
  },

  // Romanian URL translations
  ro: {
    'about': 'despre',
    'album': 'album',
    'applications': 'aplicatii',
    'artist': 'artist',
    'change-password': 'schimba-parola',
    'contact': 'contact',
    'discover': 'descopera',
    'discover-music': 'descopera-musica',
    'favorites': 'preferate',
    'feedback': 'feedback',
    'forgot-password': 'uitat-parola',
    'genres': 'genuri',
    'login': 'login',
    'notifications': 'notificari',
    'pages': 'pagini',
    'privacy-policy': 'politica-de-confidentialitate',
    'profile': 'profil',
    'radios': 'radio',
    'recommendations': 'recomandari',
    'records': 'inregistrari',
    'regions': 'regiuni',
    'request-station': 'solicita-statie',
    'settings': 'setari',
    'signup': 'inscriere',
    'song': 'cancion',
    'station': 'statie',
    'stations': 'staties',
    'terms-and-conditions': 'termeni-si-conditii',
    'trending': 'tendinte',
    'users': 'utilizatori',
  },

  // Russian URL translations
  ru: {
    'about': 'ob',
    'album': 'albom',
    'applications': 'prilozheniya',
    'artist': 'artist',
    'change-password': 'pomenyat-parol',
    'contact': 'kontakt',
    'discover': 'otkryt',
    'discover-music': 'otkryt-muzyku',
    'favorites': 'izbrannoe',
    'feedback': 'obratnaya-svyaz',
    'forgot-password': 'zabyl-parol',
    'genres': 'zhanry',
    'login': 'login',
    'notifications': 'opoveshcheniya',
    'pages': 'stranitsy',
    'privacy-policy': 'politika-konfidentsialnosti',
    'profile': 'profil',
    'radios': 'radio',
    'recommendations': 'rekomendatsii',
    'records': 'zapisi',
    'regions': 'regiony',
    'request-station': 'zapros-stantsiyu',
    'settings': 'nastroiki',
    'signup': 'signup',
    'song': 'pesnya',
    'station': 'stantsiya',
    'stations': 'stantsii',
    'terms-and-conditions': 'usloviya-i-polozheniya',
    'trending': 'populyarnye',
    'users': 'polzovateli',
  },

  // Slovak URL translations
  sk: {
    'about': 'o-nas',
    'album': 'album',
    'applications': 'aplikacie',
    'artist': 'umelci',
    'change-password': 'zmenit-heslo',
    'contact': 'kontakt',
    'discover': 'objav',
    'discover-music': 'objav-music',
    'favorites': 'oblubene',
    'feedback': 'spatna-vazba',
    'forgot-password': 'zabudol-heslo',
    'genres': 'zanre',
    'login': 'login',
    'notifications': 'oznamenia',
    'pages': 'stranky',
    'privacy-policy': 'zmluva-o-sukromi',
    'profile': 'profil',
    'radios': 'radia',
    'recommendations': 'odporucania',
    'records': 'nahravky',
    'regions': 'regiony',
    'request-station': 'poziadat-stanicu',
    'settings': 'nastavenia',
    'signup': 'registracia',
    'song': 'piesen',
    'station': 'stanica',
    'stations': 'stanice',
    'terms-and-conditions': 'podmienky',
    'trending': 'trendy',
    'users': 'uzivatelia',
  },

  // Slovenian URL translations
  sl: {
    'about': 'o-nas',
    'album': 'album',
    'applications': 'aplikacije',
    'artist': 'umetnik',
    'change-password': 'spremeni-geslo',
    'contact': 'kontakt',
    'discover': 'odkrij',
    'discover-music': 'odkrij-muziko',
    'favorites': 'najljubše',
    'feedback': 'povratne-informacije',
    'forgot-password': 'pozabljeno-geslo',
    'genres': 'zvrsti',
    'login': 'login',
    'notifications': 'obvestila',
    'pages': 'strani',
    'privacy-policy': 'politika-zasebnosti',
    'profile': 'profil',
    'radios': 'radia',
    'recommendations': 'priporočila',
    'records': 'zapisi',
    'regions': 'regije',
    'request-station': 'zahteva-postajo',
    'settings': 'nastavitve',
    'signup': 'signup',
    'song': 'pesem',
    'station': 'postaja',
    'stations': 'postaje',
    'terms-and-conditions': 'pogoji-in-določila',
    'trending': 'priljubljeno',
    'users': 'uporabniki',
  },

  // Somali URL translations
  so: {
    'about': 'ku-saabsan',
    'album': 'album',
    'applications': 'barnaamijyada',
    'artist': 'fannaan',
    'change-password': 'beddel-password',
    'contact': 'la-xiriir',
    'discover': 'soo-hel',
    'discover-music': 'soo-hel-muusig',
    'favorites': 'jaceylka',
    'feedback': 'faallo',
    'forgot-password': 'illaaw-password',
    'genres': 'noocyada',
    'login': 'login',
    'notifications': 'ogaysiis',
    'pages': 'bogagga',
    'privacy-policy': 'sharciyada-khaaska',
    'profile': 'profile',
    'radios': 'raadiyeyaasha',
    'recommendations': 'talooyin',
    'records': 'diiwaanka',
    'regions': 'gobollada',
    'request-station': 'codso-station',
    'settings': 'dejin',
    'signup': 'signup',
    'song': 'hees',
    'station': 'station',
    'stations': 'stations',
    'terms-and-conditions': 'shuruudaha-iyo-xaaladaha',
    'trending': 'iska-wareegaya',
    'users': 'isticmaaleyaasha',
  },

  // Albanian URL translations
  sq: {
    'about': 'rreth',
    'album': 'album',
    'applications': 'aplikacione',
    'artist': 'artist',
    'change-password': 'ndrysho-fjalekalimin',
    'contact': 'kontakti',
    'discover': 'zbulo',
    'discover-music': 'zbulo-muzike',
    'favorites': 'te-dashurat',
    'feedback': 'komentet',
    'forgot-password': 'harrove-fjalekalimin',
    'genres': 'zhanret',
    'login': 'login',
    'notifications': 'njoftimet',
    'pages': 'faqet',
    'privacy-policy': 'politika-e-privates',
    'profile': 'profili',
    'radios': 'radio',
    'recommendations': 'rekomandimet',
    'records': 'rekordet',
    'regions': 'rajone',
    'request-station': 'kerko-stacion',
    'settings': 'csettings',
    'signup': 'signup',
    'song': 'kenge',
    'station': 'stacion',
    'stations': 'stacione',
    'terms-and-conditions': 'termet-dhe-kushtet',
    'trending': 'trending',
    'users': 'përdoruesit',
  },

  // Serbian URL translations
  sr: {
    'about': 'o-nama',
    'album': 'album',
    'applications': 'aplikacije',
    'artist': 'umetnik',
    'change-password': 'promeni-lozinku',
    'contact': 'kontakt',
    'discover': 'otkrij',
    'discover-music': 'otkrij-muziku',
    'favorites': 'omiljeni',
    'feedback': 'povratne-informacije',
    'forgot-password': 'zaboravljena-lozinka',
    'genres': 'žanrovi',
    'login': 'login',
    'notifications': 'obaveštenja',
    'pages': 'stranice',
    'privacy-policy': 'politika-privatnosti',
    'profile': 'profil',
    'radios': 'radio-stanice',
    'recommendations': 'preporuke',
    'records': 'zapisi',
    'regions': 'regioni',
    'request-station': 'zahtev-za-stanicu',
    'settings': 'podešavanja',
    'signup': 'registracija',
    'song': 'pesma',
    'station': 'stanica',
    'stations': 'stanice',
    'terms-and-conditions': 'uslovi-korišćenja',
    'trending': 'aktuelno',
    'users': 'korisnici',
  },

  // Swedish URL translations
  sv: {
    'about': 'om',
    'album': 'album',
    'applications': 'applikationer',
    'artist': 'artist',
    'change-password': 'byta-losenord',
    'contact': 'kontakt',
    'discover': 'upptäck',
    'discover-music': 'upptack-musik',
    'favorites': 'favoriter',
    'feedback': 'feedback',
    'forgot-password': 'glomt-losenord',
    'genres': 'genrer',
    'login': 'login',
    'notifications': 'notifikationer',
    'pages': 'sidor',
    'privacy-policy': 'integritetspolicy',
    'profile': 'profil',
    'radios': 'radios',
    'recommendations': 'rekommendationer',
    'records': 'skivor',
    'regions': 'regioner',
    'request-station': 'begar-station',
    'settings': 'inställningar',
    'signup': 'registrera',
    'song': 'låt',
    'station': 'station',
    'stations': 'stationer',
    'terms-and-conditions': 'villkor',
    'trending': 'trending',
    'users': 'användare',
  },

  // Tamil URL translations
  ta: {
    'about': 'பற்றி',
    'album': 'ஆல்பம்',
    'applications': 'பயன்பாடுகள்',
    'artist': 'கலைஞர்',
    'change-password': 'கடவுச்சொல்-மாற்று',
    'contact': 'தொடர்பு',
    'discover': 'கண்டுபிடி',
    'discover-music': 'இசை-கண்டுபிடி',
    'favorites': 'விருப்பங்கள்',
    'feedback': 'பின்னூட்டம்',
    'forgot-password': 'மறந்த-கடவுச்சொல்',
    'genres': 'பிரிவுகள்',
    'login': 'login',
    'notifications': 'அறிக்கைகள்',
    'pages': 'பக்கம்',
    'privacy-policy': 'தனியுரிமை-அடிப்படைகள்',
    'profile': 'சுயவிவரம்',
    'radios': 'ரேடியோ',
    'recommendations': 'பரிந்துரைகள்',
    'records': 'பதிவுகள்',
    'regions': 'பிராந்தியங்கள்',
    'request-station': 'கோரிக்கை-நிலையம்',
    'settings': 'அமைப்புகள்',
    'signup': 'signup',
    'song': 'பாடல்',
    'station': 'நிலையம்',
    'stations': 'நிலைகள்',
    'terms-and-conditions': 'விதிமுறைகள்-மற்றும்-நிலைகள்',
    'trending': 'பிரபலமானது',
    'users': 'பயனர்',
  },

  // Thai URL translations
  th: {
    'about': 'เกี่ยวกับ',
    'album': 'อัลบั้ม',
    'applications': 'แอปพลิเคชัน',
    'artist': 'ศิลปิน',
    'change-password': 'เปลี่ยนรหัสผ่าน',
    'contact': 'ติดต่อ',
    'discover': 'ค้นพบ',
    'discover-music': 'ค้นพบเพลง',
    'favorites': 'รายการโปรด',
    'feedback': 'ข้อเสนอแนะ',
    'forgot-password': 'ลืมรหัสผ่าน',
    'genres': 'ประเภท',
    'login': 'login',
    'notifications': 'การแจ้งเตือน',
    'pages': 'หน้า',
    'privacy-policy': 'นโยบายความเป็นส่วนตัว',
    'profile': 'โปรไฟล์',
    'radios': 'วิทยุ',
    'recommendations': 'คำแนะนำ',
    'records': 'บันทึก',
    'regions': 'ภูมิภาค',
    'request-station': 'ขอสถานี',
    'settings': 'การตั้งค่า',
    'signup': 'สมัครสมาชิก',
    'song': 'เพลง',
    'station': 'สถานี',
    'stations': 'สถานี',
    'terms-and-conditions': 'เงื่อนไขการใช้งาน',
    'trending': 'มาแรง',
    'users': 'ผู้ใช้',
  },

  // Turkish URL translations
  tr: {
    'about': 'hakkinda',
    'album': 'album',
    'applications': 'uygulamalar',
    'artist': 'sanatci',
    'change-password': 'sifre-degistir',
    'contact': 'iletisim',
    'discover': 'keşfet',
    'discover-music': 'muzik-keşfet',
    'favorites': 'favoriler',
    'feedback': 'geri-bildirim',
    'forgot-password': 'sifremi-unuttum',
    'genres': 'turler',
    'login': 'login',
    'notifications': 'bildirimler',
    'pages': 'sayfalar',
    'privacy-policy': 'gizlilik-politikasi',
    'profile': 'profil',
    'radios': 'radyo',
    'recommendations': 'tavsiyeler',
    'records': 'kayitlar',
    'regions': 'bolgeler',
    'request-station': 'istek-istasyonu',
    'settings': 'ayarlar',
    'signup': 'kayit-ol',
    'song': 'sarki',
    'station': 'istasyon',
    'stations': 'istasyonlar',
    'terms-and-conditions': 'sartlar-ve-kosullar',
    'trending': 'trend',
    'users': 'kullanicilar',
  },

  // Chinese (Simplified) URL translations
  zh: {
    'about': '关于',
    'album': '专辑',
    'applications': '应用',
    'artist': '艺术家',
    'change-password': '更改密码',
    'contact': '联系',
    'discover': '发现',
    'discover-music': '发现音乐',
    'favorites': '收藏',
    'feedback': '反馈',
    'forgot-password': '忘记密码',
    'genres': '类型',
    'login': 'login',
    'notifications': '通知',
    'pages': '页面',
    'privacy-policy': '隐私政策',
    'profile': '个人资料',
    'radios': '电台',
    'recommendations': '推荐',
    'records': '记录',
    'regions': '地区',
    'request-station': '请求电台',
    'settings': '设置',
    'signup': '注册',
    'song': '歌曲',
    'station': '电台',
    'stations': '电台',
    'terms-and-conditions': '条款与条件',
    'trending': '热门',
    'users': '用户',
  },

  // Chinese (Simplified) URL translations
  'zh-CN': {
    'about': '关于',
    'album': '专辑',
    'applications': '应用',
    'artist': '艺术家',
    'change-password': '更改密码',
    'contact': '联系',
    'discover': '发现',
    'discover-music': '发现音乐',
    'favorites': '收藏',
    'feedback': '反馈',
    'forgot-password': '忘记密码',
    'genres': '类型',
    'login': 'login',
    'notifications': '通知',
    'pages': '页面',
    'privacy-policy': '隐私政策',
    'profile': '个人资料',
    'radios': '电台',
    'recommendations': '推荐',
    'records': '记录',
    'regions': '地区',
    'request-station': '请求电台',
    'settings': '设置',
    'signup': '注册',
    'song': '歌曲',
    'station': '电台',
    'stations': '电台',
    'terms-and-conditions': '条款与条件',
    'trending': '热门',
    'users': '用户',
  },

  // Afrikaans URL translations
  af: {
    'about': 'oor',
    'album': 'album',
    'applications': 'toepassings',
    'artist': 'kunstenaar',
    'change-password': 'verander-wagwoord',
    'contact': 'kontak',
    'discover': 'ontdek',
    'discover-music': 'ontdek-musiek',
    'favorites': 'gunstelinge',
    'feedback': 'terugvoer',
    'forgot-password': 'vergeet-wagwoord',
    'genres': 'genres',
    'login': 'login',
    'notifications': 'kennisgewings',
    'pages': 'bladsye',
    'privacy-policy': 'privaatheidsbeleid',
    'profile': 'profiel',
    'radios': "radio's",
    'recommendations': 'aanbevelings',
    'records': 'plate',
    'regions': 'streke',
    'request-station': 'versoek-stasie',
    'settings': 'instellings',
    'signup': 'signup',
    'song': 'lied',
    'station': 'stasie',
    'stations': 'stasies',
    'terms-and-conditions': 'bepalings-en-voorwaardes',
    'trending': 'neigings',
    'users': 'gebruikers',
  },

  // Amharic URL translations
  am: {
    'about': 'ስለ',
    'album': 'አልበም',
    'applications': 'መተግበሪያዎች',
    'artist': 'አርቲስት',
    'change-password': 'የይለፍ-ቃል-ለውጥ',
    'contact': 'እውቂያ',
    'discover': 'ማስፈላለግ',
    'discover-music': 'ሙዚቃ-ማስፈላለግ',
    'favorites': 'ተወዳጆች',
    'feedback': 'አስተያየት',
    'forgot-password': 'የይለፍ-ቃል-ረሳ',
    'genres': 'አይነቶች',
    'login': 'login',
    'notifications': 'ማሳወቂያዎች',
    'pages': 'ገጾች',
    'privacy-policy': 'ግላዊነት-መመሪያ',
    'profile': 'መገለጫ',
    'radios': 'ራዲዮዎች',
    'recommendations': 'ማስታወሻዎች',
    'records': 'መዝገቦች',
    'regions': 'ክልሎች',
    'request-station': 'ጥያቄ-ጣቢያ',
    'settings': 'ቅንብሮች',
    'signup': 'signup',
    'song': 'መዝሙር',
    'station': 'ጣቢያ',
    'stations': 'ጣቢያዎች',
    'terms-and-conditions': 'ውሎች-እና-ሁኔታዎች',
    'trending': 'ታዋቂ',
    'users': 'ተጠቃሚዎች',
  },

  // Bengali URL translations
  bn: {
    'about': 'সম্পর্কে',
    'album': 'অ্যালবাম',
    'applications': 'অ্যাপ্লিকেশন',
    'artist': 'শিল্পী',
    'change-password': 'পাসওয়ার্ড-পরিবর্তন',
    'contact': 'যোগাযোগ',
    'discover': 'আবিষ্কার',
    'discover-music': 'সঙ্গীত-আবিষ্কার',
    'favorites': 'প্রিয়',
    'feedback': 'প্রতিক্রিয়া',
    'forgot-password': 'পাসওয়ার্ড-ভুলে-গেছি',
    'genres': 'ধরন',
    'login': 'login',
    'notifications': 'বিজ্ঞপ্তি',
    'pages': 'পৃষ্ঠা',
    'privacy-policy': 'গোপনীয়তা-নীতি',
    'profile': 'প্রোফাইল',
    'radios': 'রেডিও',
    'recommendations': 'প্রস্তাবনা',
    'records': 'রেকর্ড',
    'regions': 'অঞ্চল',
    'request-station': 'অনুরোধ-স্টেশন',
    'settings': 'সেটিংস',
    'signup': 'signup',
    'song': 'গান',
    'station': 'স্টেশন',
    'stations': 'স্টেশনসমূহ',
    'terms-and-conditions': 'শর্তাবলী',
    'trending': 'প্রবণতা',
    'users': 'ব্যবহারকারী',
  },

  // Czech URL translations
  cs: {
    'about': 'o',
    'album': 'album',
    'applications': 'aplikace',
    'artist': 'umělec',
    'change-password': 'změna-hesla',
    'contact': 'kontakt',
    'discover': 'objevit',
    'discover-music': 'objevit-hudbu',
    'favorites': 'oblíbené',
    'feedback': 'zpětná-vazba',
    'forgot-password': 'zapomenuté-heslo',
    'genres': 'žánry',
    'login': 'login',
    'notifications': 'oznámení',
    'pages': 'stránky',
    'privacy-policy': 'zásady-ochrany-soukromí',
    'profile': 'profil',
    'radios': 'rádia',
    'recommendations': 'doporučení',
    'records': 'záznamy',
    'regions': 'regiony',
    'request-station': 'žádost-o-stanici',
    'settings': 'nastavení',
    'signup': 'signup',
    'song': 'píseň',
    'station': 'stanice',
    'stations': 'stanice',
    'terms-and-conditions': 'podmínky',
    'trending': 'trend',
    'users': 'uživatelé',
  },

  // Danish URL translations
  da: {
    'about': 'om',
    'album': 'album',
    'applications': 'applikationer',
    'artist': 'kunstner',
    'change-password': 'skift-adgangskode',
    'contact': 'kontakt',
    'discover': 'opdage',
    'discover-music': 'opdage-musik',
    'favorites': 'favoritter',
    'feedback': 'feedback',
    'forgot-password': 'glemt-adgangskode',
    'genres': 'genrer',
    'login': 'login',
    'notifications': 'meddelelser',
    'pages': 'sider',
    'privacy-policy': 'privatlivspolitik',
    'profile': 'profil',
    'radios': 'radioer',
    'recommendations': 'anbefalinger',
    'records': 'plader',
    'regions': 'regioner',
    'request-station': 'anmod-om-station',
    'settings': 'indstillinger',
    'signup': 'signup',
    'song': 'sang',
    'station': 'station',
    'stations': 'stationer',
    'terms-and-conditions': 'vilkår-og-betingelser',
    'trending': 'trending',
    'users': 'brugere',
  },

  // Estonian URL translations
  et: {
    'about': 'meist',
    'album': 'album',
    'applications': 'rakendused',
    'artist': 'artist',
    'change-password': 'muuda-parool',
    'contact': 'kontakt',
    'discover': 'avasta',
    'discover-music': 'avasta-muusika',
    'favorites': 'lemmikud',
    'feedback': 'tagasiside',
    'forgot-password': 'unustasid-parooli',
    'genres': 'žanrid',
    'login': 'login',
    'notifications': 'teavitused',
    'pages': 'lehed',
    'privacy-policy': 'privaatsuspoliitika',
    'profile': 'profiil',
    'radios': 'raadiod',
    'recommendations': 'soovitused',
    'records': 'salvestused',
    'regions': 'piirkonnad',
    'request-station': 'soovi-jaam',
    'settings': 'seaded',
    'signup': 'signup',
    'song': 'laul',
    'station': 'jaam',
    'stations': 'jaamad',
    'terms-and-conditions': 'tingimused',
    'trending': 'trendid',
    'users': 'kasutajad',
  },

  // Gujarati URL translations
  gu: {
    'about': 'વિશે',
    'album': 'આલ્બમ',
    'applications': 'એપ્લિકેશન્સ',
    'artist': 'કલાકાર',
    'change-password': 'પાસવર્ડ-બદલો',
    'contact': 'સંપર્ક',
    'discover': 'શોધો',
    'discover-music': 'સંગીત-શોધો',
    'favorites': 'મનપસંદ',
    'feedback': 'પ્રતિસાદ',
    'forgot-password': 'પાસવર્ડ-ભૂલ્યા',
    'genres': 'પ્રકારો',
    'login': 'login',
    'notifications': 'સૂચનાઓ',
    'pages': 'પાનાં',
    'privacy-policy': 'ગોપનીયતા-નીતિ',
    'profile': 'પ્રોફાઇલ',
    'radios': 'રેડિયો',
    'recommendations': 'ભલામણો',
    'records': 'રેકોર્ડ્સ',
    'regions': 'પ્રદેશો',
    'request-station': 'સ્ટેશન-વિનંતી',
    'settings': 'સેટિંગ્સ',
    'signup': 'signup',
    'song': 'ગીત',
    'station': 'સ્ટેશન',
    'stations': 'સ્ટેશનો',
    'terms-and-conditions': 'શરતો',
    'trending': 'ટ્રેન્ડિંગ',
    'users': 'વપરાશકર્તાઓ',
  },

  // Kannada URL translations
  kn: {
    'about': 'ಬಗ್ಗೆ',
    'album': 'ಆಲ್ಬಮ್',
    'applications': 'ಅನ್ವಯಿಕೆಗಳು',
    'artist': 'ಕಲಾವಿದ',
    'change-password': 'ಗುಪ್ತಪದ-ಬದಲಿಸಿ',
    'contact': 'ಸಂಪರ್ಕ',
    'discover': 'ಹುಡುಕಿ',
    'discover-music': 'ಸಂಗೀತ-ಹುಡುಕಿ',
    'favorites': 'ಮೆಚ್ಚಿನವು',
    'feedback': 'ಪ್ರತಿಕ್ರಿಯೆ',
    'forgot-password': 'ಗುಪ್ತಪದ-ಮರೆತಿರಾ',
    'genres': 'ಶೈಲಿಗಳು',
    'login': 'login',
    'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'pages': 'ಪುಟಗಳು',
    'privacy-policy': 'ಗೌಪ್ಯತೆ-ನೀತಿ',
    'profile': 'ಪ್ರೊಫೈಲ್',
    'radios': 'ರೇಡಿಯೋಗಳು',
    'recommendations': 'ಶಿಫಾರಸುಗಳು',
    'records': 'ದಾಖಲೆಗಳು',
    'regions': 'ಪ್ರದೇಶಗಳು',
    'request-station': 'ನಿಲ್ದಾಣ-ವಿನಂತಿ',
    'settings': 'ಸೆಟ್ಟಿಂಗ್ಗಳು',
    'signup': 'signup',
    'song': 'ಹಾಡು',
    'station': 'ನಿಲ್ದಾಣ',
    'stations': 'ನಿಲ್ದಾಣಗಳು',
    'terms-and-conditions': 'ನಿಯಮಗಳು',
    'trending': 'ಟ್ರೆಂಡಿಂಗ್',
    'users': 'ಬಳಕೆದಾರರು',
  },

  // Lithuanian URL translations
  lt: {
    'about': 'apie',
    'album': 'albumas',
    'applications': 'programos',
    'artist': 'atlikėjas',
    'change-password': 'keisti-slaptazodi',
    'contact': 'kontaktai',
    'discover': 'atrasti',
    'discover-music': 'atrasti-muzika',
    'favorites': 'mėgstamiausi',
    'feedback': 'atsiliepimai',
    'forgot-password': 'pamiršote-slaptazodi',
    'genres': 'žanrai',
    'login': 'login',
    'notifications': 'pranešimai',
    'pages': 'puslapiai',
    'privacy-policy': 'privatumo-politika',
    'profile': 'profilis',
    'radios': 'radijo',
    'recommendations': 'rekomendacijos',
    'records': 'įrašai',
    'regions': 'regionai',
    'request-station': 'prašyti-stoties',
    'settings': 'nustatymai',
    'signup': 'signup',
    'song': 'daina',
    'station': 'stotis',
    'stations': 'stotys',
    'terms-and-conditions': 'sąlygos',
    'trending': 'populiaru',
    'users': 'naudotojai',
  },

  // Latvian URL translations
  lv: {
    'about': 'par',
    'album': 'albums',
    'applications': 'lietotnes',
    'artist': 'mākslinieks',
    'change-password': 'mainīt-paroli',
    'contact': 'kontakti',
    'discover': 'atklāt',
    'discover-music': 'atklāt-mūziku',
    'favorites': 'iecienītākie',
    'feedback': 'atsauksmes',
    'forgot-password': 'aizmirsi-paroli',
    'genres': 'žanri',
    'login': 'login',
    'notifications': 'paziņojumi',
    'pages': 'lapas',
    'privacy-policy': 'privātuma-politika',
    'profile': 'profils',
    'radios': 'radio',
    'recommendations': 'ieteikumi',
    'records': 'ieraksti',
    'regions': 'reģioni',
    'request-station': 'pieprasīt-staciju',
    'settings': 'iestatījumi',
    'signup': 'signup',
    'song': 'dziesma',
    'station': 'stacija',
    'stations': 'stacijas',
    'terms-and-conditions': 'noteikumi',
    'trending': 'tendences',
    'users': 'lietotāji',
  },

  // Malayalam URL translations
  ml: {
    'about': 'kurichu',
    'album': 'albham',
    'applications': 'aplikeshans',
    'artist': 'kalakaaran',
    'change-password': 'password-matam',
    'contact': 'sambandham',
    'discover': 'kandethuka',
    'discover-music': 'sangeetham-kandethuka',
    'favorites': 'ishtangal',
    'feedback': 'prathikaranam',
    'forgot-password': 'password-marannu',
    'genres': 'vibhagangal',
    'login': 'login',
    'notifications': 'arivukal',
    'pages': 'pusthakal',
    'privacy-policy': 'gopaneeyatha-nayam',
    'profile': 'prathiphalam',
    'radios': 'vayikkal',
    'recommendations': 'suparishakal',
    'records': 'rekordukal',
    'regions': 'pradeshangal',
    'request-station': 'avasya-station',
    'settings': 'sadhanangal',
    'signup': 'signup',
    'song': 'paattu',
    'station': 'nilayam',
    'stations': 'nilayangal',
    'terms-and-conditions': 'niyamangal',
    'trending': 'pravalikkunna',
    'users': 'upayogikalk',
  },

  // Marathi URL translations
  mr: {
    'about': 'vishay',
    'album': 'albham',
    'applications': 'arj',
    'artist': 'kalakar',
    'change-password': 'password-badal',
    'contact': 'sampark',
    'discover': 'shodh',
    'discover-music': 'sangeet-shodh',
    'favorites': 'avarj',
    'feedback': 'pratikriya',
    'forgot-password': 'password-visarla',
    'genres': 'prakare',
    'login': 'login',
    'notifications': 'suchna',
    'pages': 'pahile',
    'privacy-policy': 'gopniyata-niti',
    'profile': 'pratibimb',
    'radios': 'radio',
    'recommendations': 'suparisha',
    'records': 'rekord',
    'regions': 'kshatre',
    'request-station': 'vinanti-station',
    'settings': 'sugandha',
    'signup': 'signup',
    'song': 'gaane',
    'station': 'steshan',
    'stations': 'steshane',
    'terms-and-conditions': 'sharte',
    'trending': 'prashiddh',
    'users': 'vaparak',
  },

  // Punjabi URL translations
  pa: {
    'about': 'bare',
    'album': 'albham',
    'applications': 'arjiyan',
    'artist': 'kalakar',
    'change-password': 'password-badal',
    'contact': 'sampark',
    'discover': 'khoj',
    'discover-music': 'sangeet-khoj',
    'favorites': 'pasand',
    'feedback': 'pratiphal',
    'forgot-password': 'password-bhul',
    'genres': 'prakaar',
    'login': 'login',
    'notifications': 'sujna',
    'pages': 'panne',
    'privacy-policy': 'nijta-niti',
    'profile': 'pratibimb',
    'radios': 'radio',
    'recommendations': 'sifarish',
    'records': 'rekard',
    'regions': 'khetar',
    'request-station': 'benti-station',
    'settings': 'sajavat',
    'signup': 'signup',
    'song': 'geet',
    'station': 'steshan',
    'stations': 'steshan',
    'terms-and-conditions': 'sharte',
    'trending': 'prashiddh',
    'users': 'upbhogta',
  },

  // Swahili URL translations
  sw: {
    'about': 'kuhusu',
    'album': 'albamu',
    'applications': 'maombi',
    'artist': 'msanii',
    'change-password': 'badilisha-nenosiri',
    'contact': 'mawasiliano',
    'discover': 'gundua',
    'discover-music': 'gundua-muziki',
    'favorites': 'vipendwa',
    'feedback': 'maoni',
    'forgot-password': 'sahau-nenosiri',
    'genres': 'aina',
    'login': 'login',
    'notifications': 'arifa',
    'pages': 'kurasa',
    'privacy-policy': 'sera-ya-faraga',
    'profile': 'wasifu',
    'radios': 'redio',
    'recommendations': 'mapendekezo',
    'records': 'rekodi',
    'regions': 'maeneo',
    'request-station': 'omba-stesheni',
    'settings': 'mipangilio',
    'signup': 'signup',
    'song': 'wimbo',
    'station': 'stesheni',
    'stations': 'stesheni',
    'terms-and-conditions': 'masharti',
    'trending': 'mwelekeo',
    'users': 'watumiaji',
  },

  // Telugu URL translations
  te: {
    'about': 'gurinchi',
    'album': 'albham',
    'applications': 'darakastu',
    'artist': 'kalakaarudu',
    'change-password': 'password-marpu',
    'contact': 'sambandham',
    'discover': 'kanugondu',
    'discover-music': 'sangeetam-kanugondu',
    'favorites': 'ishtalu',
    'feedback': 'pratikriya',
    'forgot-password': 'password-marichi',
    'genres': 'vargalu',
    'login': 'login',
    'notifications': 'suchanalu',
    'pages': 'patalu',
    'privacy-policy': 'gopaneeyata-niti',
    'profile': 'pratibimbam',
    'radios': 'vayikalu',
    'recommendations': 'sifarshulu',
    'records': 'rekardlu',
    'regions': 'pranthalu',
    'request-station': 'korika-station',
    'settings': 'sadhanalu',
    'signup': 'signup',
    'song': 'paata',
    'station': 'steshan',
    'stations': 'steshanlu',
    'terms-and-conditions': 'niyamalu',
    'trending': 'pramukhyam',
    'users': 'viniyogadarulu',
  },

  // Filipino URL translations
  tl: {
    'about': 'tungkol',
    'album': 'album',
    'applications': 'mga-aplikasyon',
    'artist': 'artista',
    'change-password': 'palitan-ang-password',
    'contact': 'makipag-ugnayan',
    'discover': 'tuklasin',
    'discover-music': 'tuklasin-ang-musika',
    'favorites': 'paborito',
    'feedback': 'puna',
    'forgot-password': 'nakalimutan-ang-password',
    'genres': 'mga-genre',
    'login': 'login',
    'notifications': 'mga-abiso',
    'pages': 'mga-pahina',
    'privacy-policy': 'patakaran-sa-privacy',
    'profile': 'profile',
    'radios': 'mga-radyo',
    'recommendations': 'mga-rekomendasyon',
    'records': 'mga-rekord',
    'regions': 'mga-rehiyon',
    'request-station': 'humiling-ng-istasyon',
    'settings': 'mga-setting',
    'signup': 'signup',
    'song': 'kanta',
    'station': 'istasyon',
    'stations': 'mga-istasyon',
    'terms-and-conditions': 'mga-tuntunin-at-kundisyon',
    'trending': 'nauuso',
    'users': 'mga-gumagamit',
  },

  // Ukrainian URL translations
  uk: {
    'about': 'про-нас',
    'album': 'альбом',
    'applications': 'додатки',
    'artist': 'артист',
    'change-password': 'змінити-пароль',
    'contact': 'контакт',
    'discover': 'відкрити',
    'discover-music': 'відкрити-музику',
    'favorites': 'улюблене',
    'feedback': 'відгуки',
    'forgot-password': 'забули-пароль',
    'genres': 'жанри',
    'login': 'login',
    'notifications': 'сповіщення',
    'pages': 'сторінки',
    'privacy-policy': 'політика-конфіденційності',
    'profile': 'профіль',
    'radios': 'радіо',
    'recommendations': 'рекомендації',
    'records': 'записи',
    'regions': 'регіони',
    'request-station': 'запит-станції',
    'settings': 'налаштування',
    'signup': 'signup',
    'song': 'пісня',
    'station': 'станція',
    'stations': 'станції',
    'terms-and-conditions': 'умови-та-положення',
    'trending': 'тренди',
    'users': 'користувачі',
  },

  // Urdu URL translations
  ur: {
    'about': 'کے-بارے-میں',
    'album': 'البم',
    'applications': 'ایپلیکیشنز',
    'artist': 'فنکار',
    'change-password': 'پاسورڈ-تبدیل-کریں',
    'contact': 'رابطہ',
    'discover': 'دریافت',
    'discover-music': 'موسیقی-دریافت-کریں',
    'favorites': 'پسندیدہ',
    'feedback': 'رائے',
    'forgot-password': 'پاسورڈ-بھول-گئے',
    'genres': 'اصناف',
    'login': 'login',
    'notifications': 'اطلاعات',
    'pages': 'صفحات',
    'privacy-policy': 'رازداری-کی-پالیسی',
    'profile': 'پروفائل',
    'radios': 'ریڈیوز',
    'recommendations': 'سفارشات',
    'records': 'ریکارڈز',
    'regions': 'علاقے',
    'request-station': 'اسٹیشن-کی-درخواست',
    'settings': 'ترتیبات',
    'signup': 'signup',
    'song': 'گانا',
    'station': 'اسٹیشن',
    'stations': 'اسٹیشنز',
    'terms-and-conditions': 'شرائط-و-ضوابط',
    'trending': 'رجحانات',
    'users': 'صارفین',
  },

  // Vietnamese URL translations
  vi: {
    'about': 've-chung-toi',
    'album': 'album',
    'applications': 'ung-dung',
    'artist': 'nghe-si',
    'change-password': 'doi-mat-khau',
    'contact': 'lien-he',
    'discover': 'kham-pha',
    'discover-music': 'kham-pha-nhac',
    'favorites': 'yeu-thich',
    'feedback': 'phan-hoi',
    'forgot-password': 'quen-mat-khau',
    'genres': 'the-loai',
    'login': 'login',
    'notifications': 'thong-bao',
    'pages': 'trang',
    'privacy-policy': 'chinh-sach-bao-mat',
    'profile': 'ho-so',
    'radios': 'radio',
    'recommendations': 'de-xuat',
    'records': 'ghi-am',
    'regions': 'khu-vuc',
    'request-station': 'yeu-cau-dai',
    'settings': 'cai-dat',
    'signup': 'signup',
    'song': 'bai-hat',
    'station': 'dai',
    'stations': 'cac-dai',
    'terms-and-conditions': 'dieu-khoan-va-dieu-kien',
    'trending': 'xu-huong',
    'users': 'nguoi-dung',
  },

  // Zulu URL translations
  zu: {
    'about': 'mayelana',
    'album': 'i-albhamu',
    'applications': 'izicelo',
    'artist': 'umculi',
    'change-password': 'shintsha-iphasiwedi',
    'contact': 'xhumana',
    'discover': 'thola',
    'discover-music': 'thola-umculo',
    'favorites': 'okuthandwa',
    'feedback': 'impendulo',
    'forgot-password': 'ukhohlwe-iphasiwedi',
    'genres': 'izinhlobo',
    'login': 'login',
    'notifications': 'izaziso',
    'pages': 'amakhasi',
    'privacy-policy': 'inqubomgomo-yobumfihlo',
    'profile': 'iphrofayela',
    'radios': 'iziteshi',
    'recommendations': 'izincomo',
    'records': 'irekhodi',
    'regions': 'izifunda',
    'request-station': 'cela-isiteshi',
    'settings': 'izilungiselelo',
    'signup': 'signup',
    'song': 'ingoma',
    'station': 'isiteshi',
    'stations': 'iziteshi',
    'terms-and-conditions': 'imigomo-nemibandela',
    'trending': 'okuvelele',
    'users': 'abasebenzisi',
  },


};

// Reverse translation map (translated URL segment -> English) - PER LANGUAGE
export const REVERSE_URL_TRANSLATIONS: Record<string, Record<string, string>> = {};

// GLOBAL Reverse translation map (any translated segment -> English + source language)
// Used for cross-language URL normalization: /de/istasyon/... → detect istasyon is Turkish → normalize to /de/sender/...
export interface GlobalReverseMapping {
  english: string;
  sourceLanguage: string;
}
export const GLOBAL_REVERSE_URL_TRANSLATIONS: Map<string, GlobalReverseMapping> = new Map();

// Build both per-language and global reverse maps on initialization
for (const [lang, translations] of Object.entries(URL_TRANSLATIONS)) {
  REVERSE_URL_TRANSLATIONS[lang] = {};
  for (const [english, translated] of Object.entries(translations)) {
    // Per-language map
    REVERSE_URL_TRANSLATIONS[lang][translated] = english;
    
    // Global map - only add if not already present (first language wins for conflicts)
    // English segments themselves are also added
    if (!GLOBAL_REVERSE_URL_TRANSLATIONS.has(translated)) {
      GLOBAL_REVERSE_URL_TRANSLATIONS.set(translated, { english, sourceLanguage: lang });
    }
  }
}

// Also add English segments themselves to global map (for completeness)
const englishSegments = ['about', 'album', 'applications', 'artist', 'change-password', 'contact', 
  'discover', 'discover-music', 'favorites', 'feedback', 'forgot-password', 'genres', 'login',
  'notifications', 'pages', 'privacy-policy', 'profile', 'radios', 'recommendations', 'records',
  'regions', 'request-station', 'settings', 'signup', 'song', 'station', 'stations', 
  'terms-and-conditions', 'trending', 'users'];
for (const segment of englishSegments) {
  if (!GLOBAL_REVERSE_URL_TRANSLATIONS.has(segment)) {
    GLOBAL_REVERSE_URL_TRANSLATIONS.set(segment, { english: segment, sourceLanguage: 'en' });
  }
}


/**
 * Normalize a URL path to the correct translated form for the target language.
 * Handles cross-language URL corrections: /de/istasyon/slug → /de/sender/slug
 * 
 * @param urlPath - The full URL path (e.g., "/de/istasyon/damar-turk-fm")
 * @param targetLanguage - The language code from the URL (e.g., "de")
 * @returns { normalized: string, needsRedirect: boolean } - The normalized path and whether a redirect is needed
 */
export function normalizeUrlForLanguage(urlPath: string, targetLanguage: string): { normalized: string; needsRedirect: boolean } {
  const segments = urlPath.split('/').filter(Boolean);
  
  // First segment is language code, skip it
  if (segments.length === 0) {
    return { normalized: urlPath, needsRedirect: false };
  }
  
  // Check if first segment is the language code
  const firstSegment = segments[0].toLowerCase();
  const isFirstSegmentLangCode = URL_TRANSLATIONS[firstSegment] !== undefined || firstSegment === 'en';
  
  let pathSegments: string[];
  if (isFirstSegmentLangCode) {
    pathSegments = segments.slice(1); // Skip language prefix
  } else {
    pathSegments = segments;
  }
  
  if (pathSegments.length === 0) {
    return { normalized: urlPath, needsRedirect: false };
  }
  
  let needsRedirect = false;
  const normalizedSegments: string[] = [];
  
  for (const segment of pathSegments) {
    // Decode URL-encoded characters
    let decodedSegment = segment;
    try {
      decodedSegment = decodeURIComponent(segment);
    } catch (e) {
      // Use original if decoding fails
    }
    
    // Check if this segment exists in global reverse map
    const globalMapping = GLOBAL_REVERSE_URL_TRANSLATIONS.get(decodedSegment);
    
    if (globalMapping) {
      // This is a known translatable segment
      const { english, sourceLanguage } = globalMapping;
      
      // Check if segment is already in correct language
      const correctTranslation = URL_TRANSLATIONS[targetLanguage]?.[english] || english;
      
      if (decodedSegment !== correctTranslation) {
        // Segment is in wrong language, needs redirect
        needsRedirect = true;
        normalizedSegments.push(correctTranslation);
      } else {
        // Segment is correct
        normalizedSegments.push(decodedSegment);
      }
    } else {
      // Not a translatable segment (e.g., station slug like "damar-turk-fm")
      normalizedSegments.push(decodedSegment);
    }
  }
  
  // Reconstruct path with language prefix
  const languagePrefix = isFirstSegmentLangCode ? `/${targetLanguage}` : '';
  const normalized = `${languagePrefix}/${normalizedSegments.join('/')}`;
  
  return { normalized, needsRedirect };
}

/**
 * Translate a URL path segment from English to the target language
 * PRIORITY: Database translations > Static file translations
 */
export function translateUrlSegment(segment: string, targetLanguage: string): string {
  // Check database translations first (admin-configured, highest priority)
  if (databaseUrlTranslationsCache) {
    const key = `${targetLanguage}:${segment}`;
    const dbTranslation = databaseUrlTranslationsCache.get(key);
    if (dbTranslation) {
      return dbTranslation;
    }
  }
  
  // Fall back to static file translations
  return URL_TRANSLATIONS[targetLanguage]?.[segment] || segment;
}

/**
 * Reverse translate a URL path segment from target language back to English
 */
export function reverseTranslateUrlSegment(segment: string, sourceLanguage: string): string {
  return REVERSE_URL_TRANSLATIONS[sourceLanguage]?.[segment] || segment;
}

/**
 * Translate a full URL path from English to target language
 */
export function translateUrl(urlPath: string, targetLanguage: string): string {
  if (!URL_TRANSLATIONS[targetLanguage]) {
    return urlPath;
  }

  const segments = urlPath.split('/').filter(Boolean);
  const translatedSegments = segments.map(segment => {
    // CRITICAL FIX: Check if the whole segment is a translatable key FIRST
    // This prevents "discover-music" from being split and incorrectly translated as "entdecken-music"
    const wholeSegmentTranslation = URL_TRANSLATIONS[targetLanguage]?.[segment];
    if (wholeSegmentTranslation) {
      return wholeSegmentTranslation;
    }
    
    // Only try splitting for compound paths if no exact match exists
    // Extract slug from paths like "station-slug" or "genre-slug"
    const parts = segment.split('-');
    const firstPart = parts[0];
    
    // Try to translate the first part
    const translated = URL_TRANSLATIONS[targetLanguage]?.[firstPart];
    if (translated && parts.length > 1) {
      // Reconstruct with translated prefix + original slug
      return `${translated}-${parts.slice(1).join('-')}`;
    } else if (translated) {
      return translated;
    }
    
    // No translation found, return original segment
    return segment;
  });

  return '/' + translatedSegments.join('/');
}

/**
 * Reverse translate a URL path from target language back to English
 * CRITICAL: Checks database translations FIRST for admin-configured custom paths
 */
export function reverseTranslateUrl(urlPath: string, sourceLanguage: string): string {
  const segments = urlPath.split('/').filter(Boolean);
  const englishSegments = segments.map(segment => {
    // CRITICAL: Decode URL-encoded characters (e.g., %D5%BD%D5%BF%D5%A1%D6%81%D5%AB%D5%A1 → ստացիա)
    let decodedSegment = segment;
    try {
      decodedSegment = decodeURIComponent(segment);
    } catch (e) {
      // If decoding fails, use original segment
      console.warn('Failed to decode URL segment:', segment, e);
    }
    
    // PRIORITY 1: Check database reverse translations FIRST (admin-configured)
    if (databaseReverseTranslationsCache) {
      const reverseKey = `${sourceLanguage}:${decodedSegment}`;
      const dbTranslation = databaseReverseTranslationsCache.get(reverseKey);
      if (dbTranslation) {
        return dbTranslation;
      }
    }
    
    // PRIORITY 2: Check static file reverse translations
    if (REVERSE_URL_TRANSLATIONS[sourceLanguage]) {
      const wholeSegmentTranslation = REVERSE_URL_TRANSLATIONS[sourceLanguage]?.[decodedSegment];
      if (wholeSegmentTranslation) {
        return wholeSegmentTranslation;
      }
    }
    
    // Don't translate station slugs - they should pass through as-is
    // Station slugs are already in the correct format and don't need translation
    return decodedSegment;
  });

  const result = '/' + englishSegments.join('/');
  return result;
}

// === DATABASE URL TRANSLATIONS LOADER ===

/**
 * Set database URL translations cache (called during server startup)
 * Builds both forward and reverse translation caches
 */
export function setDatabaseUrlTranslations(translations: Map<string, string>) {
  databaseUrlTranslationsCache = translations;
  
  // Build reverse translation cache
  // Forward map key: "es:stations" → "emisoras-radio"
  // Reverse map key: "es:emisoras-radio" → "stations"
  databaseReverseTranslationsCache = new Map<string, string>();
  
  Array.from(translations.entries()).forEach(([key, translatedPath]) => {
    // Key format is "languageCode:englishPath"
    const [languageCode, englishPath] = key.split(':');
    if (languageCode && englishPath && databaseReverseTranslationsCache) {
      const reverseKey = `${languageCode}:${translatedPath}`;
      databaseReverseTranslationsCache.set(reverseKey, englishPath);
    }
  });
  
}

/**
 * Load database URL translations (server-side only)
 */
export async function loadDatabaseUrlTranslations(): Promise<void> {
  // Only run on server-side
  if (typeof window !== 'undefined') return;
  
  try {
    const { performanceCache } = await import('../server/performance-cache');
    const translations = await performanceCache.getUrlTranslations();
    setDatabaseUrlTranslations(translations);
  } catch (error) {
    console.error('❌ Failed to load database URL translations:', error);
  }
}

/**
 * Get translated URL path (checks database first, then static file)
 * Priority: Database translations > Static file translations
 */
export function getTranslatedPath(languageCode: string, englishPath: string): string {
  // Check database translations first (admin-configured, highest priority)
  if (databaseUrlTranslationsCache) {
    const key = `${languageCode}:${englishPath}`;
    const dbTranslation = databaseUrlTranslationsCache.get(key);
    if (dbTranslation) {
      return dbTranslation;
    }
  }
  
  // Fall back to static file translations
  return URL_TRANSLATIONS[languageCode]?.[englishPath] || englishPath;
}
