/**
 * Seed the 15 required SEO translation keys for every active sitemap language.
 *
 * Without all 15 keys in the Translation collection a language fails
 * hasCompleteSeoTranslations() → its sitemap returns 410 Gone → Google/Bing
 * never discovers URLs for that language.
 *
 * Called at boot AFTER seedSeoTranslationKeys() so the TranslationKey
 * documents are guaranteed to exist before we upsert against them.
 * All upserts are idempotent — safe to run on every restart.
 */


import { CacheManager } from '../cache';
import { logger } from '../utils/logger';
import { pgLocalization } from '../data/postgres-localization-store';

// 15 required keys (mirrors REQUIRED_STATION_SEO_KEYS + REQUIRED_HOMEPAGE_SEO_KEYS)
type SeoKeyName =
  | 'default_station_about'
  | 'from'
  | 'genres'
  | 'station_additional_info'
  | 'live_radio'
  | 'online_radio'
  | 'radio_streaming'
  | 'hero_worlds_best_radio'
  | 'hero_over_100_countries'
  | 'hero_listen_everywhere'
  | 'nav_genres'
  | 'nav_regions'
  | 'nav_stations'
  | 'popular_genres_title'
  | 'popular_countries_title';

type LangSeoValues = Record<SeoKeyName, string>;

// ---------------------------------------------------------------------------
// Translations — 56 languages (English is seeded by seedSeoTranslationKeys,
// Turkish by seedTurkishUiTranslations; both are included here as upserts are
// idempotent and ensure the values remain consistent across reboots).
// ---------------------------------------------------------------------------
const LANG_SEO_TRANSLATIONS: Record<string, LangSeoValues> = {
  tr: {
    default_station_about: '{station_name} istasyonunu Mega Radio üzerinden ücretsiz dinle. 120+ ülkeden canlı radyo yayını.',
    from: 'dan',
    genres: 'Türler',
    station_additional_info: "Mega Radio'da ücretsiz dinle. 60.000+ radyo istasyonu, 120+ ülke.",
    live_radio: 'canlı radyo',
    online_radio: 'çevrimiçi radyo',
    radio_streaming: 'radyo yayını',
    hero_worlds_best_radio: 'Mega Radio: 120 Ülkeden Ücretsiz Canlı Radyo Yayını',
    hero_over_100_countries: '120+ ülkeden 60.000+ radyo istasyonu',
    hero_listen_everywhere: 'Her yerde, her zaman ücretsiz dinle',
    nav_genres: 'Türler',
    nav_regions: 'Ülkeler',
    nav_stations: 'İstasyonlar',
    popular_genres_title: 'Popüler Radyo Türleri',
    popular_countries_title: 'Ülkelere Göre Radyo İstasyonları',
  },
  es: {
    default_station_about: 'Escucha {station_name} en vivo en Mega Radio. Transmisión de radio en vivo gratuita desde 120+ países.',
    from: 'de',
    genres: 'Géneros',
    station_additional_info: 'Escucha gratis en Mega Radio. 60.000+ emisoras de radio de 120+ países.',
    live_radio: 'radio en vivo',
    online_radio: 'radio online',
    radio_streaming: 'transmisión de radio',
    hero_worlds_best_radio: 'Mega Radio: Radio en Vivo Gratis de 120 Países',
    hero_over_100_countries: '60.000+ emisoras de radio de 120+ países',
    hero_listen_everywhere: 'Escucha en cualquier lugar, en cualquier momento, gratis',
    nav_genres: 'Géneros',
    nav_regions: 'Regiones',
    nav_stations: 'Emisoras',
    popular_genres_title: 'Géneros de Radio Populares',
    popular_countries_title: 'Emisoras de Radio por País',
  },
  fr: {
    default_station_about: 'Écoutez {station_name} en direct sur Mega Radio. Streaming radio gratuit depuis 120+ pays.',
    from: 'de',
    genres: 'Genres',
    station_additional_info: 'Écoutez gratuitement sur Mega Radio. 60 000+ stations de radio de 120+ pays.',
    live_radio: 'radio en direct',
    online_radio: 'radio en ligne',
    radio_streaming: 'streaming radio',
    hero_worlds_best_radio: 'Mega Radio : Radio en Direct Gratuite de 120 Pays',
    hero_over_100_countries: '60 000+ stations de radio de 120+ pays',
    hero_listen_everywhere: 'Écoutez partout, à tout moment, gratuitement',
    nav_genres: 'Genres',
    nav_regions: 'Régions',
    nav_stations: 'Stations',
    popular_genres_title: 'Genres Radio Populaires',
    popular_countries_title: 'Stations Radio par Pays',
  },
  de: {
    default_station_about: 'Höre {station_name} live auf Mega Radio. Kostenloser Live-Radio-Stream aus 120+ Ländern.',
    from: 'aus',
    genres: 'Genres',
    station_additional_info: 'Kostenlos hören auf Mega Radio. 60.000+ Radiosender aus 120+ Ländern.',
    live_radio: 'Live-Radio',
    online_radio: 'Online-Radio',
    radio_streaming: 'Radio-Streaming',
    hero_worlds_best_radio: 'Mega Radio: Kostenloses Live-Radio aus 120 Ländern',
    hero_over_100_countries: '60.000+ Radiosender aus 120+ Ländern',
    hero_listen_everywhere: 'Überall, jederzeit, kostenlos hören',
    nav_genres: 'Genres',
    nav_regions: 'Regionen',
    nav_stations: 'Sender',
    popular_genres_title: 'Beliebte Radio-Genres',
    popular_countries_title: 'Radiosender nach Land',
  },
  ar: {
    default_station_about: 'استمع إلى {station_name} مباشرة على Mega Radio. بث راديو حي مجاني من أكثر من 120 دولة.',
    from: 'من',
    genres: 'أنواع',
    station_additional_info: 'استمع مجاناً على Mega Radio. أكثر من 60,000 محطة راديو من أكثر من 120 دولة.',
    live_radio: 'راديو مباشر',
    online_radio: 'راديو إنترنت',
    radio_streaming: 'بث راديو',
    hero_worlds_best_radio: 'Mega Radio: راديو حي مجاني من 120 دولة',
    hero_over_100_countries: 'أكثر من 60,000 محطة راديو من أكثر من 120 دولة',
    hero_listen_everywhere: 'استمع في أي مكان، في أي وقت، مجاناً',
    nav_genres: 'أنواع',
    nav_regions: 'المناطق',
    nav_stations: 'المحطات',
    popular_genres_title: 'أنواع الراديو الشعبية',
    popular_countries_title: 'محطات الراديو حسب الدولة',
  },
  it: {
    default_station_about: 'Ascolta {station_name} in diretta su Mega Radio. Streaming radio live gratuito da 120+ paesi.',
    from: 'da',
    genres: 'Generi',
    station_additional_info: 'Ascolta gratis su Mega Radio. 60.000+ stazioni radio da 120+ paesi.',
    live_radio: 'radio in diretta',
    online_radio: 'radio online',
    radio_streaming: 'streaming radio',
    hero_worlds_best_radio: 'Mega Radio: Radio Live Gratuita da 120 Paesi',
    hero_over_100_countries: '60.000+ stazioni radio da 120+ paesi',
    hero_listen_everywhere: 'Ascolta ovunque, in qualsiasi momento, gratuitamente',
    nav_genres: 'Generi',
    nav_regions: 'Regioni',
    nav_stations: 'Stazioni',
    popular_genres_title: 'Generi Radio Popolari',
    popular_countries_title: 'Stazioni Radio per Paese',
  },
  pt: {
    default_station_about: 'Ouça {station_name} ao vivo no Mega Radio. Streaming de rádio ao vivo gratuito de 120+ países.',
    from: 'de',
    genres: 'Gêneros',
    station_additional_info: 'Ouça grátis no Mega Radio. 60.000+ estações de rádio de 120+ países.',
    live_radio: 'rádio ao vivo',
    online_radio: 'rádio online',
    radio_streaming: 'streaming de rádio',
    hero_worlds_best_radio: 'Mega Radio: Rádio ao Vivo Gratuito de 120 Países',
    hero_over_100_countries: '60.000+ estações de rádio de 120+ países',
    hero_listen_everywhere: 'Ouça em qualquer lugar, a qualquer hora, de graça',
    nav_genres: 'Gêneros',
    nav_regions: 'Regiões',
    nav_stations: 'Estações',
    popular_genres_title: 'Gêneros de Rádio Populares',
    popular_countries_title: 'Estações de Rádio por País',
  },
  nl: {
    default_station_about: 'Luister naar {station_name} live op Mega Radio. Gratis live radiostreaming uit 120+ landen.',
    from: 'uit',
    genres: 'Genres',
    station_additional_info: 'Luister gratis op Mega Radio. 60.000+ radiostations uit 120+ landen.',
    live_radio: 'live radio',
    online_radio: 'online radio',
    radio_streaming: 'radiostreaming',
    hero_worlds_best_radio: 'Mega Radio: Gratis Live Radio uit 120 Landen',
    hero_over_100_countries: '60.000+ radiostations uit 120+ landen',
    hero_listen_everywhere: 'Luister overal, altijd, gratis',
    nav_genres: 'Genres',
    nav_regions: "Regio's",
    nav_stations: 'Stations',
    popular_genres_title: 'Populaire Radiogenres',
    popular_countries_title: 'Radiostations per Land',
  },
  ru: {
    default_station_about: 'Слушайте {station_name} в прямом эфире на Mega Radio. Бесплатное прямое радиовещание из 120+ стран.',
    from: 'из',
    genres: 'Жанры',
    station_additional_info: 'Слушайте бесплатно на Mega Radio. 60 000+ радиостанций из 120+ стран.',
    live_radio: 'прямое радио',
    online_radio: 'онлайн-радио',
    radio_streaming: 'радиостриминг',
    hero_worlds_best_radio: 'Mega Radio: Бесплатное Прямое Радио из 120 Стран',
    hero_over_100_countries: '60 000+ радиостанций из 120+ стран',
    hero_listen_everywhere: 'Слушайте везде, в любое время, бесплатно',
    nav_genres: 'Жанры',
    nav_regions: 'Регионы',
    nav_stations: 'Станции',
    popular_genres_title: 'Популярные Радиожанры',
    popular_countries_title: 'Радиостанции по Странам',
  },
  pl: {
    default_station_about: 'Słuchaj {station_name} na żywo na Mega Radio. Bezpłatne transmisje radiowe na żywo z 120+ krajów.',
    from: 'z',
    genres: 'Gatunki',
    station_additional_info: 'Słuchaj bezpłatnie na Mega Radio. 60 000+ stacji radiowych z 120+ krajów.',
    live_radio: 'radio na żywo',
    online_radio: 'radio online',
    radio_streaming: 'streaming radiowy',
    hero_worlds_best_radio: 'Mega Radio: Bezpłatne Radio na Żywo z 120 Krajów',
    hero_over_100_countries: '60 000+ stacji radiowych z 120+ krajów',
    hero_listen_everywhere: 'Słuchaj wszędzie, o każdej porze, za darmo',
    nav_genres: 'Gatunki',
    nav_regions: 'Regiony',
    nav_stations: 'Stacje',
    popular_genres_title: 'Popularne Gatunki Radiowe',
    popular_countries_title: 'Stacje Radiowe według Kraju',
  },
  sv: {
    default_station_about: 'Lyssna på {station_name} live på Mega Radio. Gratis direktsändning från 120+ länder.',
    from: 'från',
    genres: 'Genrer',
    station_additional_info: 'Lyssna gratis på Mega Radio. 60 000+ radiostationer från 120+ länder.',
    live_radio: 'direktradio',
    online_radio: 'onlineradio',
    radio_streaming: 'radiostreaming',
    hero_worlds_best_radio: 'Mega Radio: Gratis Direktradio från 120 Länder',
    hero_over_100_countries: '60 000+ radiostationer från 120+ länder',
    hero_listen_everywhere: 'Lyssna var som helst, när som helst, gratis',
    nav_genres: 'Genrer',
    nav_regions: 'Regioner',
    nav_stations: 'Stationer',
    popular_genres_title: 'Populära Radiogenrer',
    popular_countries_title: 'Radiostationer per Land',
  },
  da: {
    default_station_about: 'Lyt til {station_name} live på Mega Radio. Gratis live radiostreaming fra 120+ lande.',
    from: 'fra',
    genres: 'Genrer',
    station_additional_info: 'Lyt gratis på Mega Radio. 60.000+ radiostationer fra 120+ lande.',
    live_radio: 'direkte radio',
    online_radio: 'onlineradio',
    radio_streaming: 'radiostreaming',
    hero_worlds_best_radio: 'Mega Radio: Gratis Direkte Radio fra 120 Lande',
    hero_over_100_countries: '60.000+ radiostationer fra 120+ lande',
    hero_listen_everywhere: 'Lyt overalt, når som helst, gratis',
    nav_genres: 'Genrer',
    nav_regions: 'Regioner',
    nav_stations: 'Stationer',
    popular_genres_title: 'Populære Radiogenrer',
    popular_countries_title: 'Radiostationer efter Land',
  },
  no: {
    default_station_about: 'Lytt til {station_name} direkte på Mega Radio. Gratis direkteradiostrømming fra 120+ land.',
    from: 'fra',
    genres: 'Sjangere',
    station_additional_info: 'Lytt gratis på Mega Radio. 60 000+ radiostasjoner fra 120+ land.',
    live_radio: 'direkteradio',
    online_radio: 'nettradio',
    radio_streaming: 'radiostrømming',
    hero_worlds_best_radio: 'Mega Radio: Gratis Direkteradio fra 120 Land',
    hero_over_100_countries: '60 000+ radiostasjoner fra 120+ land',
    hero_listen_everywhere: 'Lytt overalt, når som helst, gratis',
    nav_genres: 'Sjangere',
    nav_regions: 'Regioner',
    nav_stations: 'Stasjoner',
    popular_genres_title: 'Populære Radiosjangere',
    popular_countries_title: 'Radiostasjoner etter Land',
  },
  fi: {
    default_station_about: 'Kuuntele {station_name} suorana Mega Radiossa. Ilmainen suora radiolähetys yli 120 maasta.',
    from: 'kohteesta',
    genres: 'Genret',
    station_additional_info: 'Kuuntele ilmaiseksi Mega Radiossa. 60 000+ radioasemaa yli 120 maasta.',
    live_radio: 'suora radio',
    online_radio: 'verkkoradio',
    radio_streaming: 'radiosuoratoisto',
    hero_worlds_best_radio: 'Mega Radio: Ilmainen Suora Radio 120 Maasta',
    hero_over_100_countries: '60 000+ radioasemaa yli 120 maasta',
    hero_listen_everywhere: 'Kuuntele kaikkialla, milloin tahansa, ilmaiseksi',
    nav_genres: 'Genret',
    nav_regions: 'Alueet',
    nav_stations: 'Asemat',
    popular_genres_title: 'Suosituimmat Radiogenret',
    popular_countries_title: 'Radioasemat maittain',
  },
  el: {
    default_station_about: 'Ακούστε {station_name} ζωντανά στο Mega Radio. Δωρεάν ζωντανή ραδιοφωνική μετάδοση από 120+ χώρες.',
    from: 'από',
    genres: 'Είδη',
    station_additional_info: 'Ακούστε δωρεάν στο Mega Radio. 60.000+ ραδιοφωνικοί σταθμοί από 120+ χώρες.',
    live_radio: 'ζωντανό ράδιο',
    online_radio: 'διαδικτυακό ράδιο',
    radio_streaming: 'ροή ραδιοφώνου',
    hero_worlds_best_radio: 'Mega Radio: Δωρεάν Ζωντανό Ράδιο από 120 Χώρες',
    hero_over_100_countries: '60.000+ ραδιοφωνικοί σταθμοί από 120+ χώρες',
    hero_listen_everywhere: 'Ακούστε παντού, οποτεδήποτε, δωρεάν',
    nav_genres: 'Είδη',
    nav_regions: 'Περιοχές',
    nav_stations: 'Σταθμοί',
    popular_genres_title: 'Δημοφιλή Ραδιοφωνικά Είδη',
    popular_countries_title: 'Ραδιοφωνικοί Σταθμοί ανά Χώρα',
  },
  hu: {
    default_station_about: 'Hallgasd a {station_name} élőben a Mega Radio-n. Ingyenes élő rádióközvetítés 120+ országból.',
    from: 'innen',
    genres: 'Műfajok',
    station_additional_info: 'Hallgass ingyen a Mega Radio-n. 60 000+ rádióállomás 120+ országból.',
    live_radio: 'élő rádió',
    online_radio: 'online rádió',
    radio_streaming: 'rádió streaming',
    hero_worlds_best_radio: 'Mega Radio: Ingyenes Élő Rádió 120 Országból',
    hero_over_100_countries: '60 000+ rádióállomás 120+ országból',
    hero_listen_everywhere: 'Hallgass bárhol, bármikor, ingyenesen',
    nav_genres: 'Műfajok',
    nav_regions: 'Régiók',
    nav_stations: 'Állomások',
    popular_genres_title: 'Népszerű Rádióműfajok',
    popular_countries_title: 'Rádióállomások Országonként',
  },
  cs: {
    default_station_about: 'Poslouchejte {station_name} živě na Mega Radio. Bezplatné živé rádio ze 120+ zemí.',
    from: 'z',
    genres: 'Žánry',
    station_additional_info: 'Poslouchejte zdarma na Mega Radio. 60 000+ rozhlasových stanic ze 120+ zemí.',
    live_radio: 'živé rádio',
    online_radio: 'online rádio',
    radio_streaming: 'rádio streaming',
    hero_worlds_best_radio: 'Mega Radio: Bezplatné Živé Rádio ze 120 Zemí',
    hero_over_100_countries: '60 000+ rozhlasových stanic ze 120+ zemí',
    hero_listen_everywhere: 'Poslouchejte kdekoli, kdykoli, zdarma',
    nav_genres: 'Žánry',
    nav_regions: 'Regiony',
    nav_stations: 'Stanice',
    popular_genres_title: 'Oblíbené Rádio Žánry',
    popular_countries_title: 'Rozhlasové Stanice podle Země',
  },
  sk: {
    default_station_about: 'Počúvajte {station_name} naživo na Mega Radio. Bezplatné živé rádio zo 120+ krajín.',
    from: 'z',
    genres: 'Žánre',
    station_additional_info: 'Počúvajte zadarmo na Mega Radio. 60 000+ rozhlasových staníc zo 120+ krajín.',
    live_radio: 'živé rádio',
    online_radio: 'online rádio',
    radio_streaming: 'rádio streaming',
    hero_worlds_best_radio: 'Mega Radio: Bezplatné Živé Rádio zo 120 Krajín',
    hero_over_100_countries: '60 000+ rozhlasových staníc zo 120+ krajín',
    hero_listen_everywhere: 'Počúvajte kdekoľvek, kedykoľvek, zadarmo',
    nav_genres: 'Žánre',
    nav_regions: 'Regióny',
    nav_stations: 'Stanice',
    popular_genres_title: 'Obľúbené Rádio Žánre',
    popular_countries_title: 'Rozhlasové Stanice podľa Krajiny',
  },
  ro: {
    default_station_about: 'Ascultă {station_name} live pe Mega Radio. Streaming radio live gratuit din 120+ țări.',
    from: 'din',
    genres: 'Genuri',
    station_additional_info: 'Ascultă gratuit pe Mega Radio. 60.000+ posturi de radio din 120+ țări.',
    live_radio: 'radio live',
    online_radio: 'radio online',
    radio_streaming: 'streaming radio',
    hero_worlds_best_radio: 'Mega Radio: Radio Live Gratuit din 120 de Țări',
    hero_over_100_countries: '60.000+ posturi de radio din 120+ țări',
    hero_listen_everywhere: 'Ascultă oriunde, oricând, gratuit',
    nav_genres: 'Genuri',
    nav_regions: 'Regiuni',
    nav_stations: 'Posturi',
    popular_genres_title: 'Genuri Radio Populare',
    popular_countries_title: 'Posturi Radio pe Țări',
  },
  bg: {
    default_station_about: 'Слушайте {station_name} на живо в Mega Radio. Безплатно радио на живо от 120+ страни.',
    from: 'от',
    genres: 'Жанрове',
    station_additional_info: 'Слушайте безплатно в Mega Radio. 60 000+ радиостанции от 120+ страни.',
    live_radio: 'живо радио',
    online_radio: 'онлайн радио',
    radio_streaming: 'радио стрийминг',
    hero_worlds_best_radio: 'Mega Radio: Безплатно Живо Радио от 120 Страни',
    hero_over_100_countries: '60 000+ радиостанции от 120+ страни',
    hero_listen_everywhere: 'Слушайте навсякъде, по всяко време, безплатно',
    nav_genres: 'Жанрове',
    nav_regions: 'Региони',
    nav_stations: 'Станции',
    popular_genres_title: 'Популярни Радиожанрове',
    popular_countries_title: 'Радиостанции по Страни',
  },
  hr: {
    default_station_about: 'Slušajte {station_name} uživo na Mega Radio. Besplatni prijenos radija uživo iz 120+ zemalja.',
    from: 'iz',
    genres: 'Žanrovi',
    station_additional_info: 'Slušajte besplatno na Mega Radio. 60 000+ radio postaja iz 120+ zemalja.',
    live_radio: 'radio uživo',
    online_radio: 'online radio',
    radio_streaming: 'radio streaming',
    hero_worlds_best_radio: 'Mega Radio: Besplatni Radio Uživo iz 120 Zemalja',
    hero_over_100_countries: '60 000+ radio postaja iz 120+ zemalja',
    hero_listen_everywhere: 'Slušajte bilo gdje, bilo kad, besplatno',
    nav_genres: 'Žanrovi',
    nav_regions: 'Regije',
    nav_stations: 'Postaje',
    popular_genres_title: 'Popularni Radio Žanrovi',
    popular_countries_title: 'Radio Postaje po Zemljama',
  },
  sr: {
    default_station_about: 'Слушајте {station_name} уживо на Mega Radio. Бесплатан пренос радија уживо из 120+ земаља.',
    from: 'из',
    genres: 'Жанрови',
    station_additional_info: 'Слушајте бесплатно на Mega Radio. 60 000+ радио станица из 120+ земаља.',
    live_radio: 'радио уживо',
    online_radio: 'онлајн радио',
    radio_streaming: 'радио стриминг',
    hero_worlds_best_radio: 'Mega Radio: Бесплатан Радио Уживо из 120 Земаља',
    hero_over_100_countries: '60 000+ радио станица из 120+ земаља',
    hero_listen_everywhere: 'Слушајте свуда, у свако доба, бесплатно',
    nav_genres: 'Жанрови',
    nav_regions: 'Региони',
    nav_stations: 'Станице',
    popular_genres_title: 'Популарни Радио Жанрови',
    popular_countries_title: 'Радио Станице по Земљама',
  },
  sl: {
    default_station_about: 'Poslušajte {station_name} v živo na Mega Radio. Brezplačen prenos radia v živo iz 120+ držav.',
    from: 'iz',
    genres: 'Zvrsti',
    station_additional_info: 'Poslušajte brezplačno na Mega Radio. 60 000+ radijskih postaj iz 120+ držav.',
    live_radio: 'radio v živo',
    online_radio: 'spletni radio',
    radio_streaming: 'radijsko pretakanje',
    hero_worlds_best_radio: 'Mega Radio: Brezplačen Radio v Živo iz 120 Držav',
    hero_over_100_countries: '60 000+ radijskih postaj iz 120+ držav',
    hero_listen_everywhere: 'Poslušajte kjerkoli, kadarkoli, brezplačno',
    nav_genres: 'Zvrsti',
    nav_regions: 'Regije',
    nav_stations: 'Postaje',
    popular_genres_title: 'Priljubljene Radijske Zvrsti',
    popular_countries_title: 'Radijske Postaje po Državah',
  },
  lv: {
    default_station_about: 'Klausieties {station_name} tiešraidē Mega Radio. Bezmaksas tiešraides radio no 120+ valstīm.',
    from: 'no',
    genres: 'Žanri',
    station_additional_info: 'Klausieties bez maksas Mega Radio. 60 000+ radio stacijas no 120+ valstīm.',
    live_radio: 'tiešraides radio',
    online_radio: 'tiešsaistes radio',
    radio_streaming: 'radio straumēšana',
    hero_worlds_best_radio: 'Mega Radio: Bezmaksas Tiešraides Radio no 120 Valstīm',
    hero_over_100_countries: '60 000+ radio stacijas no 120+ valstīm',
    hero_listen_everywhere: 'Klausieties jebkur, jebkad, bez maksas',
    nav_genres: 'Žanri',
    nav_regions: 'Reģioni',
    nav_stations: 'Stacijas',
    popular_genres_title: 'Populārie Radio Žanri',
    popular_countries_title: 'Radio Stacijas pēc Valsts',
  },
  lt: {
    default_station_about: 'Klausykite {station_name} tiesioginėje transliacijoje Mega Radio. Nemokama tiesioginė radijo transliacija iš 120+ šalių.',
    from: 'iš',
    genres: 'Žanrai',
    station_additional_info: 'Klausykite nemokamai Mega Radio. 60 000+ radijo stočių iš 120+ šalių.',
    live_radio: 'tiesioginis radijas',
    online_radio: 'internetinis radijas',
    radio_streaming: 'radijo srautas',
    hero_worlds_best_radio: 'Mega Radio: Nemokamas Tiesioginis Radijas iš 120 Šalių',
    hero_over_100_countries: '60 000+ radijo stočių iš 120+ šalių',
    hero_listen_everywhere: 'Klausykite bet kur, bet kada, nemokamai',
    nav_genres: 'Žanrai',
    nav_regions: 'Regionai',
    nav_stations: 'Stotys',
    popular_genres_title: 'Populiarūs Radijo Žanrai',
    popular_countries_title: 'Radijo Stotys pagal Šalį',
  },
  et: {
    default_station_about: 'Kuulake {station_name} otse Mega Radios. Tasuta otseülekanne 120+ riigist.',
    from: 'riigist',
    genres: 'Žanrid',
    station_additional_info: 'Kuulake tasuta Mega Radios. 60 000+ raadiojaam 120+ riigist.',
    live_radio: 'otseraadio',
    online_radio: 'veebraadio',
    radio_streaming: 'raadio voogedastus',
    hero_worlds_best_radio: 'Mega Radio: Tasuta Otseraadio 120 Riigist',
    hero_over_100_countries: '60 000+ raadiojaam 120+ riigist',
    hero_listen_everywhere: 'Kuulake kõikjal, igal ajal, tasuta',
    nav_genres: 'Žanrid',
    nav_regions: 'Piirkonnad',
    nav_stations: 'Jaamad',
    popular_genres_title: 'Populaarsed Raadiožanrid',
    popular_countries_title: 'Raadiojaamad Riikide Kaupa',
  },
  zh: {
    default_station_about: '在 Mega Radio 收听 {station_name} 直播。来自 120+ 个国家的免费直播电台。',
    from: '来自',
    genres: '流派',
    station_additional_info: '在 Mega Radio 免费收听。来自 120+ 个国家的 60,000+ 个广播电台。',
    live_radio: '直播电台',
    online_radio: '网络电台',
    radio_streaming: '电台流媒体',
    hero_worlds_best_radio: 'Mega Radio：来自 120 个国家的免费直播电台',
    hero_over_100_countries: '来自 120+ 个国家的 60,000+ 个广播电台',
    hero_listen_everywhere: '随时随地免费收听',
    nav_genres: '流派',
    nav_regions: '地区',
    nav_stations: '电台',
    popular_genres_title: '热门电台流派',
    popular_countries_title: '按国家分类的广播电台',
  },
  ja: {
    default_station_about: 'Mega Radioで{station_name}をライブで聴く。120カ国以上から無料ライブラジオストリーミング。',
    from: 'から',
    genres: 'ジャンル',
    station_additional_info: 'Mega Radioで無料でお聴きいただけます。120カ国以上の60,000以上のラジオ局。',
    live_radio: 'ライブラジオ',
    online_radio: 'オンラインラジオ',
    radio_streaming: 'ラジオストリーミング',
    hero_worlds_best_radio: 'Mega Radio：120カ国からの無料ライブラジオ',
    hero_over_100_countries: '120カ国以上から60,000以上のラジオ局',
    hero_listen_everywhere: 'どこでも、いつでも、無料で聴く',
    nav_genres: 'ジャンル',
    nav_regions: '地域',
    nav_stations: 'ラジオ局',
    popular_genres_title: '人気のラジオジャンル',
    popular_countries_title: '国別ラジオ局',
  },
  ko: {
    default_station_about: 'Mega Radio에서 {station_name}을(를) 생방송으로 들어보세요. 120개국 이상에서 무료 라디오 스트리밍.',
    from: '에서',
    genres: '장르',
    station_additional_info: 'Mega Radio에서 무료로 들어보세요. 120개국 이상의 60,000개 이상 라디오 방송국.',
    live_radio: '라이브 라디오',
    online_radio: '온라인 라디오',
    radio_streaming: '라디오 스트리밍',
    hero_worlds_best_radio: 'Mega Radio: 120개국의 무료 라이브 라디오',
    hero_over_100_countries: '120개국 이상의 60,000개 이상 라디오 방송국',
    hero_listen_everywhere: '어디서나, 언제든지, 무료로 들어보세요',
    nav_genres: '장르',
    nav_regions: '지역',
    nav_stations: '방송국',
    popular_genres_title: '인기 라디오 장르',
    popular_countries_title: '국가별 라디오 방송국',
  },
  hi: {
    default_station_about: 'Mega Radio पर {station_name} को लाइव सुनें। 120+ देशों से मुफ्त लाइव रेडियो स्ट्रीमिंग।',
    from: 'से',
    genres: 'शैलियाँ',
    station_additional_info: 'Mega Radio पर मुफ्त सुनें। 120+ देशों से 60,000+ रेडियो स्टेशन।',
    live_radio: 'लाइव रेडियो',
    online_radio: 'ऑनलाइन रेडियो',
    radio_streaming: 'रेडियो स्ट्रीमिंग',
    hero_worlds_best_radio: 'Mega Radio: 120 देशों से मुफ्त लाइव रेडियो',
    hero_over_100_countries: '120+ देशों से 60,000+ रेडियो स्टेशन',
    hero_listen_everywhere: 'कहीं भी, कभी भी, मुफ्त में सुनें',
    nav_genres: 'शैलियाँ',
    nav_regions: 'क्षेत्र',
    nav_stations: 'स्टेशन',
    popular_genres_title: 'लोकप्रिय रेडियो शैलियाँ',
    popular_countries_title: 'देश के अनुसार रेडियो स्टेशन',
  },
  th: {
    default_station_about: 'ฟัง {station_name} สดบน Mega Radio สตรีมมิ่งวิทยุสดฟรีจากกว่า 120 ประเทศ',
    from: 'จาก',
    genres: 'แนวเพลง',
    station_additional_info: 'ฟังฟรีบน Mega Radio วิทยุกว่า 60,000 สถานีจากกว่า 120 ประเทศ',
    live_radio: 'วิทยุสด',
    online_radio: 'วิทยุออนไลน์',
    radio_streaming: 'สตรีมมิ่งวิทยุ',
    hero_worlds_best_radio: 'Mega Radio: วิทยุสดฟรีจาก 120 ประเทศ',
    hero_over_100_countries: 'กว่า 60,000 สถานีวิทยุจากกว่า 120 ประเทศ',
    hero_listen_everywhere: 'ฟังทุกที่ทุกเวลาฟรี',
    nav_genres: 'แนวเพลง',
    nav_regions: 'ภูมิภาค',
    nav_stations: 'สถานี',
    popular_genres_title: 'แนวเพลงวิทยุยอดนิยม',
    popular_countries_title: 'สถานีวิทยุตามประเทศ',
  },
  vi: {
    default_station_about: 'Nghe {station_name} trực tiếp trên Mega Radio. Phát trực tiếp radio miễn phí từ 120+ quốc gia.',
    from: 'từ',
    genres: 'Thể loại',
    station_additional_info: 'Nghe miễn phí trên Mega Radio. 60.000+ đài phát thanh từ 120+ quốc gia.',
    live_radio: 'radio trực tiếp',
    online_radio: 'radio trực tuyến',
    radio_streaming: 'phát trực tuyến radio',
    hero_worlds_best_radio: 'Mega Radio: Radio Trực Tiếp Miễn Phí từ 120 Quốc Gia',
    hero_over_100_countries: '60.000+ đài phát thanh từ 120+ quốc gia',
    hero_listen_everywhere: 'Nghe mọi lúc, mọi nơi, miễn phí',
    nav_genres: 'Thể loại',
    nav_regions: 'Khu vực',
    nav_stations: 'Đài',
    popular_genres_title: 'Thể Loại Radio Phổ Biến',
    popular_countries_title: 'Đài Phát Thanh theo Quốc Gia',
  },
  id: {
    default_station_about: 'Dengarkan {station_name} secara langsung di Mega Radio. Streaming radio langsung gratis dari 120+ negara.',
    from: 'dari',
    genres: 'Genre',
    station_additional_info: 'Dengarkan gratis di Mega Radio. 60.000+ stasiun radio dari 120+ negara.',
    live_radio: 'radio langsung',
    online_radio: 'radio online',
    radio_streaming: 'streaming radio',
    hero_worlds_best_radio: 'Mega Radio: Radio Langsung Gratis dari 120 Negara',
    hero_over_100_countries: '60.000+ stasiun radio dari 120+ negara',
    hero_listen_everywhere: 'Dengarkan di mana saja, kapan saja, gratis',
    nav_genres: 'Genre',
    nav_regions: 'Wilayah',
    nav_stations: 'Stasiun',
    popular_genres_title: 'Genre Radio Populer',
    popular_countries_title: 'Stasiun Radio berdasarkan Negara',
  },
  ms: {
    default_station_about: 'Dengar {station_name} secara langsung di Mega Radio. Penstriman radio langsung percuma dari 120+ negara.',
    from: 'dari',
    genres: 'Genre',
    station_additional_info: 'Dengar percuma di Mega Radio. 60,000+ stesen radio dari 120+ negara.',
    live_radio: 'radio langsung',
    online_radio: 'radio dalam talian',
    radio_streaming: 'penstriman radio',
    hero_worlds_best_radio: 'Mega Radio: Radio Langsung Percuma dari 120 Negara',
    hero_over_100_countries: '60,000+ stesen radio dari 120+ negara',
    hero_listen_everywhere: 'Dengar di mana saja, bila-bila masa, percuma',
    nav_genres: 'Genre',
    nav_regions: 'Wilayah',
    nav_stations: 'Stesen',
    popular_genres_title: 'Genre Radio Popular',
    popular_countries_title: 'Stesen Radio mengikut Negara',
  },
  tl: {
    default_station_about: 'Pakinggan ang {station_name} nang live sa Mega Radio. Libreng live na radio streaming mula sa 120+ bansa.',
    from: 'mula sa',
    genres: 'Mga Genre',
    station_additional_info: 'Makinig nang libre sa Mega Radio. 60,000+ istasyon ng radyo mula sa 120+ bansa.',
    live_radio: 'live na radyo',
    online_radio: 'online na radyo',
    radio_streaming: 'radio streaming',
    hero_worlds_best_radio: 'Mega Radio: Libreng Live na Radyo mula sa 120 Bansa',
    hero_over_100_countries: '60,000+ istasyon ng radyo mula sa 120+ bansa',
    hero_listen_everywhere: 'Makinig kahit saan, kahit kailan, nang libre',
    nav_genres: 'Mga Genre',
    nav_regions: 'Mga Rehiyon',
    nav_stations: 'Mga Istasyon',
    popular_genres_title: 'Mga Sikat na Genre ng Radyo',
    popular_countries_title: 'Mga Istasyon ng Radyo ayon sa Bansa',
  },
  he: {
    default_station_about: 'האזינו ל-{station_name} בשידור חי ב-Mega Radio. שידור רדיו חי חינמי מ-120+ מדינות.',
    from: 'מ',
    genres: "ז'אנרים",
    station_additional_info: 'האזינו בחינם ב-Mega Radio. 60,000+ תחנות רדיו מ-120+ מדינות.',
    live_radio: 'רדיו חי',
    online_radio: 'רדיו מקוון',
    radio_streaming: 'שידור רדיו',
    hero_worlds_best_radio: 'Mega Radio: רדיו חי חינמי מ-120 מדינות',
    hero_over_100_countries: '60,000+ תחנות רדיו מ-120+ מדינות',
    hero_listen_everywhere: 'האזינו בכל מקום, בכל זמן, בחינם',
    nav_genres: "ז'אנרים",
    nav_regions: 'אזורים',
    nav_stations: 'תחנות',
    popular_genres_title: "ז'אנרי רדיו פופולריים",
    popular_countries_title: 'תחנות רדיו לפי מדינה',
  },
  fa: {
    default_station_about: 'به {station_name} به صورت زنده در Mega Radio گوش دهید. پخش زنده رادیو رایگان از ۱۲۰+ کشور.',
    from: 'از',
    genres: 'ژانرها',
    station_additional_info: 'رایگان در Mega Radio گوش دهید. بیش از ۶۰٬۰۰۰ ایستگاه رادیویی از ۱۲۰+ کشور.',
    live_radio: 'رادیو زنده',
    online_radio: 'رادیو آنلاین',
    radio_streaming: 'پخش رادیو',
    hero_worlds_best_radio: 'Mega Radio: رادیو زنده رایگان از ۱۲۰ کشور',
    hero_over_100_countries: 'بیش از ۶۰٬۰۰۰ ایستگاه رادیویی از ۱۲۰+ کشور',
    hero_listen_everywhere: 'در هر جا، هر زمان، رایگان گوش دهید',
    nav_genres: 'ژانرها',
    nav_regions: 'مناطق',
    nav_stations: 'ایستگاه‌ها',
    popular_genres_title: 'ژانرهای محبوب رادیویی',
    popular_countries_title: 'ایستگاه‌های رادیویی بر اساس کشور',
  },
  ur: {
    default_station_about: 'Mega Radio پر {station_name} کو لائیو سنیں۔ 120+ ممالک سے مفت لائیو ریڈیو سٹریمنگ۔',
    from: 'سے',
    genres: 'اصناف',
    station_additional_info: 'Mega Radio پر مفت سنیں۔ 120+ ممالک سے 60,000+ ریڈیو اسٹیشن۔',
    live_radio: 'لائیو ریڈیو',
    online_radio: 'آن لائن ریڈیو',
    radio_streaming: 'ریڈیو سٹریمنگ',
    hero_worlds_best_radio: 'Mega Radio: 120 ممالک سے مفت لائیو ریڈیو',
    hero_over_100_countries: '120+ ممالک سے 60,000+ ریڈیو اسٹیشن',
    hero_listen_everywhere: 'کہیں بھی، کبھی بھی، مفت میں سنیں',
    nav_genres: 'اصناف',
    nav_regions: 'علاقے',
    nav_stations: 'اسٹیشن',
    popular_genres_title: 'مقبول ریڈیو اصناف',
    popular_countries_title: 'ملک کے مطابق ریڈیو اسٹیشن',
  },
  bn: {
    default_station_about: 'Mega Radio-তে {station_name} লাইভ শুনুন। ১২০+ দেশ থেকে বিনামূল্যে লাইভ রেডিও স্ট্রিমিং।',
    from: 'থেকে',
    genres: 'ঘরানা',
    station_additional_info: 'Mega Radio-তে বিনামূল্যে শুনুন। ১২০+ দেশ থেকে ৬০,০০০+ রেডিও স্টেশন।',
    live_radio: 'লাইভ রেডিও',
    online_radio: 'অনলাইন রেডিও',
    radio_streaming: 'রেডিও স্ট্রিমিং',
    hero_worlds_best_radio: 'Mega Radio: ১২০ দেশ থেকে বিনামূল্যে লাইভ রেডিও',
    hero_over_100_countries: '১২০+ দেশ থেকে ৬০,০০০+ রেডিও স্টেশন',
    hero_listen_everywhere: 'যেকোনো জায়গায়, যেকোনো সময়, বিনামূল্যে শুনুন',
    nav_genres: 'ঘরানা',
    nav_regions: 'অঞ্চল',
    nav_stations: 'স্টেশন',
    popular_genres_title: 'জনপ্রিয় রেডিও ঘরানা',
    popular_countries_title: 'দেশ অনুসারে রেডিও স্টেশন',
  },
  ta: {
    default_station_about: 'Mega Radio-ல் {station_name}-ஐ நேரடியாகக் கேளுங்கள். 120+ நாடுகளில் இருந்து இலவச நேரடி வானொலி ஸ்ட்ரீமிங்.',
    from: 'இலிருந்து',
    genres: 'வகைகள்',
    station_additional_info: 'Mega Radio-ல் இலவசமாகக் கேளுங்கள். 120+ நாடுகளில் இருந்து 60,000+ வானொலி நிலையங்கள்.',
    live_radio: 'நேரடி வானொலி',
    online_radio: 'ஆன்லைன் வானொலி',
    radio_streaming: 'வானொலி ஸ்ட்ரீமிங்',
    hero_worlds_best_radio: 'Mega Radio: 120 நாடுகளில் இருந்து இலவச நேரடி வானொலி',
    hero_over_100_countries: '120+ நாடுகளில் இருந்து 60,000+ வானொலி நிலையங்கள்',
    hero_listen_everywhere: 'எங்கும், எப்போதும், இலவசமாகக் கேளுங்கள்',
    nav_genres: 'வகைகள்',
    nav_regions: 'பிராந்தியங்கள்',
    nav_stations: 'நிலையங்கள்',
    popular_genres_title: 'பிரபலமான வானொலி வகைகள்',
    popular_countries_title: 'நாடு வாரியான வானொலி நிலையங்கள்',
  },
  te: {
    default_station_about: 'Mega Radio లో {station_name}ని లైవ్‌లో వినండి. 120+ దేశాల నుండి ఉచిత లైవ్ రేడియో స్ట్రీమింగ్.',
    from: 'నుండి',
    genres: 'శైలులు',
    station_additional_info: 'Mega Radio లో ఉచితంగా వినండి. 120+ దేశాల నుండి 60,000+ రేడియో స్టేషన్లు.',
    live_radio: 'లైవ్ రేడియో',
    online_radio: 'ఆన్‌లైన్ రేడియో',
    radio_streaming: 'రేడియో స్ట్రీమింగ్',
    hero_worlds_best_radio: 'Mega Radio: 120 దేశాల నుండి ఉచిత లైవ్ రేడియో',
    hero_over_100_countries: '120+ దేశాల నుండి 60,000+ రేడియో స్టేషన్లు',
    hero_listen_everywhere: 'ఎక్కడైనా, ఎప్పుడైనా, ఉచితంగా వినండి',
    nav_genres: 'శైలులు',
    nav_regions: 'ప్రాంతాలు',
    nav_stations: 'స్టేషన్లు',
    popular_genres_title: 'ప్రసిద్ధ రేడియో శైలులు',
    popular_countries_title: 'దేశం వారీగా రేడియో స్టేషన్లు',
  },
  mr: {
    default_station_about: 'Mega Radio वर {station_name} थेट ऐका. 120+ देशांतून मोफत थेट रेडिओ स्ट्रीमिंग.',
    from: 'पासून',
    genres: 'शैली',
    station_additional_info: 'Mega Radio वर मोफत ऐका. 120+ देशांतून 60,000+ रेडिओ स्टेशन.',
    live_radio: 'थेट रेडिओ',
    online_radio: 'ऑनलाइन रेडिओ',
    radio_streaming: 'रेडिओ स्ट्रीमिंग',
    hero_worlds_best_radio: 'Mega Radio: 120 देशांतून मोफत थेट रेडिओ',
    hero_over_100_countries: '120+ देशांतून 60,000+ रेडिओ स्टेशन',
    hero_listen_everywhere: 'कुठेही, कधीही, मोफत ऐका',
    nav_genres: 'शैली',
    nav_regions: 'प्रदेश',
    nav_stations: 'स्टेशन',
    popular_genres_title: 'लोकप्रिय रेडिओ शैली',
    popular_countries_title: 'देशानुसार रेडिओ स्टेशन',
  },
  gu: {
    default_station_about: 'Mega Radio પર {station_name} સીધું સાંભળો. 120+ દેશોમાંથી મફત સીધું રેડિઓ સ્ટ્રીમિંગ.',
    from: 'થી',
    genres: 'શૈલીઓ',
    station_additional_info: 'Mega Radio પર મફત સાંભળો. 120+ દેશોમાંથી 60,000+ રેડિઓ સ્ટેશન.',
    live_radio: 'સીધું રેડિઓ',
    online_radio: 'ઓનલાઇન રેડિઓ',
    radio_streaming: 'રેડિઓ સ્ટ્રીમિંગ',
    hero_worlds_best_radio: 'Mega Radio: 120 દેશોમાંથી મફત સીધું રેડિઓ',
    hero_over_100_countries: '120+ દેશોમાંથી 60,000+ રેડિઓ સ્ટેશન',
    hero_listen_everywhere: 'ગમે ત્યાં, ગમે ત્યારે, મફત સાંભળો',
    nav_genres: 'શૈલીઓ',
    nav_regions: 'પ્રદેશો',
    nav_stations: 'સ્ટેશન',
    popular_genres_title: 'લોકપ્રિય રેડિઓ શૈલીઓ',
    popular_countries_title: 'દેશ મુજબ રેડિઓ સ્ટેશન',
  },
  kn: {
    default_station_about: 'Mega Radio ನಲ್ಲಿ {station_name} ಅನ್ನು ನೇರ ಪ್ರಸಾರದಲ್ಲಿ ಕೇಳಿ. 120+ ದೇಶಗಳಿಂದ ಉಚಿತ ನೇರ ರೇಡಿಯೊ ಸ್ಟ್ರೀಮಿಂಗ್.',
    from: 'ಇಂದ',
    genres: 'ಶೈಲಿಗಳು',
    station_additional_info: 'Mega Radio ನಲ್ಲಿ ಉಚಿತವಾಗಿ ಕೇಳಿ. 120+ ದೇಶಗಳಿಂದ 60,000+ ರೇಡಿಯೊ ಕೇಂದ್ರಗಳು.',
    live_radio: 'ನೇರ ರೇಡಿಯೊ',
    online_radio: 'ಆನ್‌ಲೈನ್ ರೇಡಿಯೊ',
    radio_streaming: 'ರೇಡಿಯೊ ಸ್ಟ್ರೀಮಿಂಗ್',
    hero_worlds_best_radio: 'Mega Radio: 120 ದೇಶಗಳಿಂದ ಉಚಿತ ನೇರ ರೇಡಿಯೊ',
    hero_over_100_countries: '120+ ದೇಶಗಳಿಂದ 60,000+ ರೇಡಿಯೊ ಕೇಂದ್ರಗಳು',
    hero_listen_everywhere: 'ಎಲ್ಲಿಯಾದರೂ, ಯಾವಾಗಲಾದರೂ, ಉಚಿತವಾಗಿ ಕೇಳಿ',
    nav_genres: 'ಶೈಲಿಗಳು',
    nav_regions: 'ಪ್ರದೇಶಗಳು',
    nav_stations: 'ಕೇಂದ್ರಗಳು',
    popular_genres_title: 'ಜನಪ್ರಿಯ ರೇಡಿಯೊ ಶೈಲಿಗಳು',
    popular_countries_title: 'ದೇಶದ ಪ್ರಕಾರ ರೇಡಿಯೊ ಕೇಂದ್ರಗಳು',
  },
  ml: {
    default_station_about: 'Mega Radio-ൽ {station_name} ലൈവ് ആയി കേൾക്കൂ. 120+ രാജ്യങ്ങളിൽ നിന്ന് സൗജന്യ ലൈവ് റേഡിയോ സ്ട്രീമിംഗ്.',
    from: 'ൽ നിന്ന്',
    genres: 'ഘടകങ്ങൾ',
    station_additional_info: 'Mega Radio-ൽ സൗജന്യമായി കേൾക്കൂ. 120+ രാജ്യങ്ങളിൽ നിന്ന് 60,000+ റേഡിയോ സ്റ്റേഷനുകൾ.',
    live_radio: 'ലൈവ് റേഡിയോ',
    online_radio: 'ഓൺലൈൻ റേഡിയോ',
    radio_streaming: 'റേഡിയോ സ്ട്രീമിംഗ്',
    hero_worlds_best_radio: 'Mega Radio: 120 രാജ്യങ്ങളിൽ നിന്ന് സൗജന്യ ലൈവ് റേഡിയോ',
    hero_over_100_countries: '120+ രാജ്യങ്ങളിൽ നിന്ന് 60,000+ റേഡിയോ സ്റ്റേഷനുകൾ',
    hero_listen_everywhere: 'എവിടെയും, എപ്പോഴും, സൗജന്യമായി കേൾക്കൂ',
    nav_genres: 'ഘടകങ്ങൾ',
    nav_regions: 'പ്രദേശങ്ങൾ',
    nav_stations: 'സ്റ്റേഷനുകൾ',
    popular_genres_title: 'ജനപ്രിയ റേഡിയോ ഘടകങ്ങൾ',
    popular_countries_title: 'രാജ്യം അനുസരിച്ച് റേഡിയോ സ്റ്റേഷനുകൾ',
  },
  pa: {
    default_station_about: "Mega Radio 'ਤੇ {station_name} ਲਾਈਵ ਸੁਣੋ। 120+ ਦੇਸ਼ਾਂ ਤੋਂ ਮੁਫ਼ਤ ਲਾਈਵ ਰੇਡੀਓ ਸਟ੍ਰੀਮਿੰਗ।",
    from: 'ਤੋਂ',
    genres: 'ਸ਼ੈਲੀਆਂ',
    station_additional_info: "Mega Radio 'ਤੇ ਮੁਫ਼ਤ ਸੁਣੋ। 120+ ਦੇਸ਼ਾਂ ਤੋਂ 60,000+ ਰੇਡੀਓ ਸਟੇਸ਼ਨ।",
    live_radio: 'ਲਾਈਵ ਰੇਡੀਓ',
    online_radio: 'ਔਨਲਾਈਨ ਰੇਡੀਓ',
    radio_streaming: 'ਰੇਡੀਓ ਸਟ੍ਰੀਮਿੰਗ',
    hero_worlds_best_radio: 'Mega Radio: 120 ਦੇਸ਼ਾਂ ਤੋਂ ਮੁਫ਼ਤ ਲਾਈਵ ਰੇਡੀਓ',
    hero_over_100_countries: '120+ ਦੇਸ਼ਾਂ ਤੋਂ 60,000+ ਰੇਡੀਓ ਸਟੇਸ਼ਨ',
    hero_listen_everywhere: 'ਕਿਤੇ ਵੀ, ਕਦੇ ਵੀ, ਮੁਫ਼ਤ ਵਿੱਚ ਸੁਣੋ',
    nav_genres: 'ਸ਼ੈਲੀਆਂ',
    nav_regions: 'ਖੇਤਰ',
    nav_stations: 'ਸਟੇਸ਼ਨ',
    popular_genres_title: 'ਪ੍ਰਸਿੱਧ ਰੇਡੀਓ ਸ਼ੈਲੀਆਂ',
    popular_countries_title: 'ਦੇਸ਼ ਅਨੁਸਾਰ ਰੇਡੀਓ ਸਟੇਸ਼ਨ',
  },
  sw: {
    default_station_about: 'Sikiliza {station_name} moja kwa moja kwenye Mega Radio. Utiririshaji wa redio moja kwa moja bila malipo kutoka nchi 120+.',
    from: 'kutoka',
    genres: 'Aina',
    station_additional_info: 'Sikiliza bure kwenye Mega Radio. Vituo vya redio 60,000+ kutoka nchi 120+.',
    live_radio: 'redio moja kwa moja',
    online_radio: 'redio mtandaoni',
    radio_streaming: 'utiririshaji wa redio',
    hero_worlds_best_radio: 'Mega Radio: Redio Moja kwa Moja Bure kutoka Nchi 120',
    hero_over_100_countries: 'Vituo vya redio 60,000+ kutoka nchi 120+',
    hero_listen_everywhere: 'Sikiliza popote, wakati wowote, bure',
    nav_genres: 'Aina',
    nav_regions: 'Maeneo',
    nav_stations: 'Vituo',
    popular_genres_title: 'Aina Maarufu za Redio',
    popular_countries_title: 'Vituo vya Redio kwa Nchi',
  },
  am: {
    default_station_about: 'Mega Radio ላይ {station_name}ን በቀጥታ ያዳምጡ። ከ120+ አገሮች ነፃ የቀጥታ ሬዲዮ ስትሪሚንግ።',
    from: 'ከ',
    genres: 'ዘውጎች',
    station_additional_info: 'Mega Radio ላይ ነፃ ያዳምጡ። ከ120+ አገሮች 60,000+ የሬዲዮ ጣቢያዎች።',
    live_radio: 'ቀጥታ ሬዲዮ',
    online_radio: 'የኢንተርኔት ሬዲዮ',
    radio_streaming: 'የሬዲዮ ስትሪሚንግ',
    hero_worlds_best_radio: 'Mega Radio: ከ120 አገሮች ነፃ ቀጥታ ሬዲዮ',
    hero_over_100_countries: 'ከ120+ አገሮች 60,000+ የሬዲዮ ጣቢያዎች',
    hero_listen_everywhere: 'በማንኛውም ቦታ፣ በማንኛውም ጊዜ፣ ነፃ ያዳምጡ',
    nav_genres: 'ዘውጎች',
    nav_regions: 'ክልሎች',
    nav_stations: 'ጣቢያዎች',
    popular_genres_title: 'ታዋቂ የሬዲዮ ዘውጎች',
    popular_countries_title: 'በአገር የሬዲዮ ጣቢያዎች',
  },
  zu: {
    default_station_about: 'Lalela i-{station_name} ngokuqondile ku-Mega Radio. Ukufafaza kwerediyo ngokuqondile mahhala kusuka emazweni angaphezu kuka-120.',
    from: 'kusuka',
    genres: 'Izinhlobo',
    station_additional_info: 'Lalela mahhala ku-Mega Radio. Iziteshi ezingaphezu kuka-60,000 kusuka emazweni angaphezu kuka-120.',
    live_radio: 'rediyo engokuqondile',
    online_radio: 'rediyo ku-inthanethi',
    radio_streaming: 'ukufafaza kwerediyo',
    hero_worlds_best_radio: 'Mega Radio: Rediyo Engokuqondile Mahhala kusuka emazweni angama-120',
    hero_over_100_countries: 'Iziteshi ezingaphezu kuka-60,000 kusuka emazweni angaphezu kuka-120',
    hero_listen_everywhere: 'Lalela noma kuphi, noma nini, mahhala',
    nav_genres: 'Izinhlobo',
    nav_regions: 'Izifunda',
    nav_stations: 'Iziteshi',
    popular_genres_title: 'Izinhlobo Zikamabonakude Ezinaziwa',
    popular_countries_title: 'Iziteshi Zikamabonakude Ngezwe',
  },
  af: {
    default_station_about: 'Luister na {station_name} regstreeks op Mega Radio. Gratis regstreekse radiostroom uit 120+ lande.',
    from: 'uit',
    genres: 'Genres',
    station_additional_info: 'Luister gratis op Mega Radio. 60 000+ radiostasies uit 120+ lande.',
    live_radio: 'regstreekse radio',
    online_radio: 'aanlynradio',
    radio_streaming: 'radiostroom',
    hero_worlds_best_radio: 'Mega Radio: Gratis Regstreekse Radio uit 120 Lande',
    hero_over_100_countries: '60 000+ radiostasies uit 120+ lande',
    hero_listen_everywhere: 'Luister oral, enige tyd, gratis',
    nav_genres: 'Genres',
    nav_regions: 'Streke',
    nav_stations: 'Stasies',
    popular_genres_title: 'Gewilde Radiogenres',
    popular_countries_title: 'Radiostasies per Land',
  },
  sq: {
    default_station_about: 'Dëgjoni {station_name} drejtpërdrejt në Mega Radio. Transmetim falas i drejtpërdrejtë nga 120+ vende.',
    from: 'nga',
    genres: 'Zhanre',
    station_additional_info: 'Dëgjoni falas në Mega Radio. 60 000+ stacione radio nga 120+ vende.',
    live_radio: 'radio drejtpërdrejt',
    online_radio: 'radio online',
    radio_streaming: 'transmetim radio',
    hero_worlds_best_radio: 'Mega Radio: Radio Drejtpërdrejt Falas nga 120 Vende',
    hero_over_100_countries: '60 000+ stacione radio nga 120+ vende',
    hero_listen_everywhere: 'Dëgjoni kudo, kurdoherë, falas',
    nav_genres: 'Zhanre',
    nav_regions: 'Rajone',
    nav_stations: 'Stacione',
    popular_genres_title: 'Zhanret Popullore të Radios',
    popular_countries_title: 'Stacionet Radio sipas Vendit',
  },
  az: {
    default_station_about: 'Mega Radio-da {station_name}-ı canlı dinləyin. 120+ ölkədən pulsuz canlı radio axını.',
    from: 'ölkəsindən',
    genres: 'Janrlar',
    station_additional_info: 'Mega Radio-da pulsuz dinləyin. 120+ ölkədən 60 000+ radio stansiyası.',
    live_radio: 'canlı radio',
    online_radio: 'onlayn radio',
    radio_streaming: 'radio axını',
    hero_worlds_best_radio: 'Mega Radio: 120 Ölkədən Pulsuz Canlı Radio',
    hero_over_100_countries: '120+ ölkədən 60 000+ radio stansiyası',
    hero_listen_everywhere: 'Harada olursan ol, nə vaxt istəsən, pulsuz dinlə',
    nav_genres: 'Janrlar',
    nav_regions: 'Bölgələr',
    nav_stations: 'Stansiyalar',
    popular_genres_title: 'Populyar Radio Janrları',
    popular_countries_title: 'Ölkə üzrə Radio Stansiyaları',
  },
  hy: {
    default_station_about: 'Լսեք {station_name}-ն ուղիղ Mega Radio-ում։ Անվճար ուղիղ ռադիոհոսք ավելի քան 120 երկրից։',
    from: 'ից',
    genres: 'Ժանրեր',
    station_additional_info: 'Լսեք անվճար Mega Radio-ում։ Ավելի քան 60,000 ռադիոկայաններ ավելի քան 120 երկրից։',
    live_radio: 'ուղիղ ռադիո',
    online_radio: 'առցանց ռադիո',
    radio_streaming: 'ռադիոհոսք',
    hero_worlds_best_radio: 'Mega Radio: Անվճար Ուղիղ Ռադիո 120 Երկրից',
    hero_over_100_countries: 'Ավելի քան 60,000 ռադիոկայաններ ավելի քան 120 երկրից',
    hero_listen_everywhere: 'Լսեք ամենուր, ցանկացած ժամանակ, անվճար',
    nav_genres: 'Ժանրեր',
    nav_regions: 'Շրջաններ',
    nav_stations: 'Կայաններ',
    popular_genres_title: 'Հայտնի Ռադիոժանրեր',
    popular_countries_title: 'Ռադիոկայաններ ըստ Երկրի',
  },
  so: {
    default_station_about: 'Ka dhegeyso {station_name} si toos ah Mega Radio. Xog-ogaanshaha raadiyaha bilaashka ah ee toos ah laga helayo waxaa ka badan 120 waddan.',
    from: 'ka',
    genres: 'Noocyada',
    station_additional_info: 'Ka dhegeyso bilaashka ah Mega Radio. Waxaa ka badan 60,000 xididdada raadiyaha laga helayo waxaa ka badan 120 waddan.',
    live_radio: 'raadiyaha tooska ah',
    online_radio: 'raadiyaha internetka',
    radio_streaming: 'streaming-ka raadiyaha',
    hero_worlds_best_radio: 'Mega Radio: Raadiyaha Bilaashka ah ee Tooska ah laga helayo 120 Waddan',
    hero_over_100_countries: 'Waxaa ka badan 60,000 xididdada raadiyaha laga helayo waxaa ka badan 120 waddan',
    hero_listen_everywhere: 'Ka dhegeyso meel kasta, mar kasta, bilaashka ah',
    nav_genres: 'Noocyada',
    nav_regions: 'Gobolada',
    nav_stations: 'Xididdada',
    popular_genres_title: 'Noocyada Raadiyaha ee Caanka ah',
    popular_countries_title: 'Xididdada Raadiyaha ee ku salaysan Wadanka',
  },
  uk: {
    default_station_about: 'Слухайте {station_name} наживо на Mega Radio. Безкоштовне пряме радіо з 120+ країн.',
    from: 'з',
    genres: 'Жанри',
    station_additional_info: 'Слухайте безкоштовно на Mega Radio. 60 000+ радіостанцій з 120+ країн.',
    live_radio: 'пряме радіо',
    online_radio: 'онлайн-радіо',
    radio_streaming: 'радіостримінг',
    hero_worlds_best_radio: 'Mega Radio: Безкоштовне Пряме Радіо з 120 Країн',
    hero_over_100_countries: '60 000+ радіостанцій з 120+ країн',
    hero_listen_everywhere: 'Слухайте будь-де, будь-коли, безкоштовно',
    nav_genres: 'Жанри',
    nav_regions: 'Регіони',
    nav_stations: 'Станції',
    popular_genres_title: 'Популярні Радіожанри',
    popular_countries_title: 'Радіостанції за Країнами',
  },
  bs: {
    default_station_about: 'Slušajte {station_name} uživo na Mega Radio. Besplatno uživo radio emitiranje iz 120+ zemalja.',
    from: 'iz',
    genres: 'Žanrovi',
    station_additional_info: 'Slušajte besplatno na Mega Radio. 60 000+ radio stanica iz 120+ zemalja.',
    live_radio: 'radio uživo',
    online_radio: 'online radio',
    radio_streaming: 'radio streaming',
    hero_worlds_best_radio: 'Mega Radio: Besplatan Radio Uživo iz 120 Zemalja',
    hero_over_100_countries: '60 000+ radio stanica iz 120+ zemalja',
    hero_listen_everywhere: 'Slušajte bilo gdje, bilo kad, besplatno',
    nav_genres: 'Žanrovi',
    nav_regions: 'Regije',
    nav_stations: 'Stanice',
    popular_genres_title: 'Popularni Radio Žanrovi',
    popular_countries_title: 'Radio Stanice po Zemaljama',
  },
};

// ---------------------------------------------------------------------------
// Seeder
// ---------------------------------------------------------------------------
export async function seedAllLanguagesSeoTranslations(): Promise<void> {
  const keys = Object.keys(LANG_SEO_TRANSLATIONS[Object.keys(LANG_SEO_TRANSLATIONS)[0]]) as SeoKeyName[];

  // Pre-load all TranslationKey docs needed by this seeder in one query.
  const keyDocs = (await pgLocalization().getKeys(keys));
  const keyMap = new Map<string, string>(keyDocs.map((d: any) => [d.key, String(d._id)]));

  // Warn but DO NOT abort if a key is missing — writing the keys that DO exist
  // is strictly better than writing nothing. A single missing key must never
  // stop all 56 languages from being seeded (this previously collapsed the
  // sitemap to /en only).
  const missingKeys = keys.filter((k) => !keyMap.has(k));
  if (missingKeys.length > 0) {
    logger.warn(`seedAllLanguagesSeoTranslations: ${missingKeys.length} TranslationKey docs not found (seeding the rest anyway). Missing: ${missingKeys.join(', ')}`);
  }

  // Boot fills gaps only. Non-empty human edits (including drafts) survive every restart.
  const totalUpserted = await pgLocalization().seedTranslationBundle(keyDocs, LANG_SEO_TRANSLATIONS, 'all-languages-seo', { bumpVersion: true });
  if (totalUpserted) await CacheManager.clearByPattern('translations');
  logger.log(`✅ seedAllLanguagesSeoTranslations: ${totalUpserted} upserts across ${Object.keys(LANG_SEO_TRANSLATIONS).length} languages`);
}
